### ISSUE TITLE
Random 

### ISSUE THREAD

**Issue by vantech14** [home-assistant/operating-system#1238]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [ ] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Intel NUC (or compatible)
- [X ] OVA (Open Virtualization Applicance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
Core
Version
core-2021.2.3

Supervisor
Version
supervisor-2021.02.11

Operating System
Home Assistant OS 5.11

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

I am currently using home assistant OS and have the following error in my log and cant seem to find a solution to the issue: 

Logger: homeassistant
Source: helpers/config_entry_oauth2_flow.py:131
First occurred: February 20, 2021, 7:28:32 PM (126 occurrences)
Last logged: 10:39:37 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 325, in async_step_discovery
    return await self.async_step_pick_implementation()
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 250, in async_step_pick_implementation
    return await self.async_step_auth()
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 274, in async_step_auth
    url = await self.flow_impl.async_generate_authorize_url(self.flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 147, in async_generate_authorize_url
    redirect_uri = self.redirect_uri
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 131, in redirect_uri
    raise RuntimeError("No current request in context")
RuntimeError: No current request in context

Any help would be appreciated.

Thanks.

**Comment by agners** [comment]
This error is thrown by Home Assistant Core, so likely not a Home Assistant OS issue. I'll transfer the issue to the correct repository.
