### ISSUE TITLE
Blue ODROID hangs with a memory problem systemd-coredump

### ISSUE THREAD

**Issue by xerxel** [home-assistant/operating-system#1298]
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [*] ODROID [C2/C4/N2(+)/XU4]
- [ ] ASUS Tinker [S]
- [ ] Generic x86-64 (like Intel NUC)
- [ ] OVA (Open Virtualization Applicance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [*] Fresh installation of release 5.12
- [ ] Updated from version x.y
- Additional information (if accessible):

## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.9.16
arch | aarch64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4868
Installed Version | 1.11.3
Stage | running
Available Repositories | 841
Installed Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | undefined

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.6
docker_version | 19.03.13
disk_total | 113.9 GB
disk_used | 14.3 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.1), Home Assistant Google Drive Backup (0.103.1), Check Home Assistant configuration (3.6.0), Duck DNS (1.12.5), File editor (5.2.0), SSH & Web Terminal (8.1.0), AdGuard Home (4.0.0), DHCP server (1.2), ESPHome (1.16.2), Log Viewer (0.9.1), Node-RED (8.2.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 6
-- | --
resources | 3
views | 10
mode | storage

</details>

**Supervisor logs:**

```
21-04-03 21:04:23 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-hassio-multicast with version 2021.04.0
21-04-03 21:04:23 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin
21-04-03 21:04:23 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_multicast application
21-04-03 21:04:23 INFO (SyncWorker_0) [supervisor.docker.multicast] Starting Multicast homeassistant/aarch64-hassio-multicast with version 2021.04.0 - Host
21-04-03 21:04:23 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-04-03 21:04:23 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/odroid-n2-homeassistant with version 2021.3.4
21-04-03 21:04:24 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 26 Home Assistant secrets
21-04-03 21:04:24 INFO (MainThread) [supervisor.hassos] Detect HassOS 5.12 / BootSlot B
21-04-03 21:04:24 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Google Assistant Webserver
21-04-03 21:04:24 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS Server DEVELOPMENT
21-04-03 21:04:24 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/cebe7a76 repository
21-04-03 21:04:24 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
21-04-03 21:04:24 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/62c7908d repository
21-04-03 21:04:24 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
21-04-03 21:04:24 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Google Assistant Webserver
21-04-03 21:04:24 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Z-Wave JS Server DEVELOPMENT
21-04-03 21:04:24 INFO (MainThread) [supervisor.store] Loading add-ons from store: 74 all - 74 new - 0 remove
21-04-03 21:04:24 INFO (MainThread) [supervisor.addons] Found 11 installed add-ons
21-04-03 21:04:24 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to sabeechen/hassio-google-drive-backup-aarch64 with version 0.103.1
21-04-03 21:04:24 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/ssh/aarch64 with version 8.1.0
21-04-03 21:04:24 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-samba with version 9.3.1
21-04-03 21:04:24 INFO (SyncWorker_6) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/adguard/aarch64 with version 4.0.0
21-04-03 21:04:24 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/node-red/aarch64 with version 8.2.1
21-04-03 21:04:24 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-duckdns with version 1.12.5
21-04-03 21:04:24 INFO (SyncWorker_7) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-configurator with version 5.2.0
21-04-03 21:04:24 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-dhcp_server with version 1.2
21-04-03 21:04:24 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to esphome/esphome-hassio-aarch64 with version 1.16.2
21-04-03 21:04:24 INFO (SyncWorker_8) [supervisor.docker.interface] Attaching to hassioaddons/log-viewer-aarch64 with version 0.9.1
21-04-03 21:04:24 INFO (SyncWorker_9) [supervisor.docker.interface] Attaching to homeassistant/aarch64-addon-check_config with version 3.6.0
21-04-03 21:04:25 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files
21-04-03 21:04:25 INFO (MainThread) [supervisor.discovery] Loaded 1 messages
21-04-03 21:04:25 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
21-04-03 21:04:25 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
21-04-03 21:04:25 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-04-03 21:04:25 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
21-04-03 21:04:25 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-04-03 21:04:25 INFO (MainThread) [__main__] Running Supervisor
21-04-03 21:04:25 INFO (MainThread) [supervisor.hassos] Rauc: B - marked slot kernel.1 as good
21-04-03 21:04:25 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
21-04-03 21:04:25 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' starting 1 add-ons
21-04-03 21:04:25 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_core_dhcp_server application
21-04-03 21:04:25 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-dhcp_server with version 1.2
21-04-03 21:04:30 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' starting 4 add-ons
21-04-03 21:04:30 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_samba application
21-04-03 21:04:31 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-samba with version 9.3.1
21-04-03 21:04:31 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_core_duckdns application
21-04-03 21:04:31 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-duckdns with version 1.12.5
21-04-03 21:04:31 WARNING (SyncWorker_8) [supervisor.docker.addon] SSH & Web Terminal running with disabled protected mode!
21-04-03 21:04:31 INFO (SyncWorker_8) [supervisor.docker.interface] Cleaning addon_a0d7b954_ssh application
21-04-03 21:04:32 INFO (SyncWorker_8) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/ssh/aarch64 with version 8.1.0
21-04-03 21:04:32 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_a0d7b954_adguard application
21-04-03 21:04:32 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/adguard/aarch64 with version 4.0.0
21-04-03 21:04:37 INFO (MainThread) [supervisor.api.security] /network/interface/default/info access from a0d7b954_adguard
21-04-03 21:04:37 INFO (MainThread) [supervisor.core] Start Home Assistant Core
21-04-03 21:04:37 INFO (SyncWorker_2) [supervisor.docker.interface] Starting homeassistant
21-04-03 21:04:38 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-04-03 21:05:32 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-04-03 21:06:04 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-04-03 21:06:04 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 5 add-ons
21-04-03 21:06:04 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_cebe7a76_hassio_google_drive_backup application
21-04-03 21:06:05 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-aarch64 with version 0.103.1
21-04-03 21:06:05 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_configurator application
21-04-03 21:06:06 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-configurator with version 5.2.0
21-04-03 21:06:06 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_a0d7b954_esphome application
21-04-03 21:06:06 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on esphome/esphome-hassio-aarch64 with version 1.16.2
21-04-03 21:06:06 INFO (SyncWorker_8) [supervisor.docker.interface] Cleaning addon_a0d7b954_logviewer application
21-04-03 21:06:07 INFO (MainThread) [supervisor.api.security] /core/info access from cebe7a76_hassio_google_drive_backup
21-04-03 21:06:07 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
21-04-03 21:06:07 INFO (SyncWorker_8) [supervisor.docker.addon] Starting Docker add-on hassioaddons/log-viewer-aarch64 with version 0.9.1
21-04-03 21:06:07 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
21-04-03 21:06:07 INFO (MainThread) [supervisor.api.security] /snapshots/26cc210a/info access from cebe7a76_hassio_google_drive_backup
21-04-03 21:06:07 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_a0d7b954_nodered application
21-04-03 21:06:07 INFO (MainThread) [supervisor.api.security] /snapshots/888420d4/info access from cebe7a76_hassio_google_drive_backup
21-04-03 21:06:07 INFO (MainThread) [supervisor.api.security] /snapshots/1d465370/info access from cebe7a76_hassio_google_drive_backup
21-04-03 21:06:07 INFO (MainThread) [supervisor.api.security] /snapshots/0d1eb540/info access from cebe7a76_hassio_google_drive_backup
21-04-03 21:06:07 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_esphome
21-04-03 21:06:08 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/node-red/aarch64 with version 8.2.1
21-04-03 21:06:10 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_logviewer
21-04-03 21:06:13 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
21-04-03 21:06:13 INFO (MainThread) [supervisor.core] Supervisor is up and running
21-04-03 21:06:13 INFO (MainThread) [supervisor.host.info] Updating local host information
21-04-03 21:06:13 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-04-03 21:06:13 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-04-03 21:06:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-04-03 21:06:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-04-03 21:06:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-04-03 21:06:13 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-04-03 21:06:13 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-04-03 21:06:13 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-04-03 21:06:13 INFO (MainThread) [supervisor.host.services] Updating service information
21-04-03 21:06:13 INFO (MainThread) [supervisor.host.network] Updating local network information
21-04-03 21:06:14 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_logviewer
21-04-03 21:06:15 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-04-03 21:06:15 INFO (MainThread) [supervisor.host] Host information reload completed
21-04-03 21:06:30 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-04-03 21:06:30 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-04-03 21:06:31 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
```

**Journal logs:**

**Kernel logs:**

**Description of problem:**

From time to time, everything will suddenly stop including core, DHCP, DNS etc. Tonight is the first time I managed to capture an error - see screenshot attached. Looks like a memory leak perhaps?

![coredump](https://user-images.githubusercontent.com/36201116/113491989-ac4e8b80-94cc-11eb-9056-45d21b831c31.jpg)

**Comment by xerxel** [comment]
Attached is the result of `journalctl -b 1 ` albeit not from the previous boot which had the crash but it does show quite a few errors.
[log.txt](https://github.com/home-assistant/operating-system/files/6253795/log.txt)

**Comment by xerxel** [comment]
OK - It just crashed again/locked up and brought the internet down due to DNS/ DHCP etc! When the system froze at around 22:52:30 there are audio errors in the log. Then a did a manual hard reboot and on startup there are lots of audio errors. Could these be a cause?

[logaudio.txt](https://github.com/home-assistant/operating-system/files/6261178/logaudio.txt)

**Comment by xerxel** [comment]
Also getting these errors in Core log:

```
2021-04-05 23:51:59 ERROR (MainThread) [homeassistant.components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 245, in _connect_loop
    await self._connect(conf)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 340, in _connect
    'Connection was re-established to Apple TV "%s"', self.atv.service.name
AttributeError: 'MrpService' object has no attribute 'name'
2021-04-05 23:51:59 ERROR (MainThread) [homeassistant.components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 245, in _connect_loop
    await self._connect(conf)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 340, in _connect
    'Connection was re-established to Apple TV "%s"', self.atv.service.name
AttributeError: 'MrpService' object has no attribute 'name'
2021-04-05 23:52:01 ERROR (MainThread) [homeassistant.components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 245, in _connect_loop
    await self._connect(conf)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 340, in _connect
    'Connection was re-established to Apple TV "%s"', self.atv.service.name
AttributeError: 'MrpService' object has no attribute 'name'
2021-04-05 23:52:03 ERROR (MainThread) [homeassistant.components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 245, in _connect_loop
    await self._connect(conf)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 340, in _connect
    'Connection was re-established to Apple TV "%s"', self.atv.service.name
AttributeError: 'MrpService' object has no attribute 'name'
2021-04-05 23:52:04 ERROR (MainThread) [homeassistant.components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 245, in _connect_loop
    await self._connect(conf)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 340, in _connect
    'Connection was re-established to Apple TV "%s"', self.atv.service.name
AttributeError: 'MrpService' object has no attribute 'name'
2021-04-05 23:52:06 ERROR (MainThread) [homeassistant.components.apple_tv] Failed to connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 245, in _connect_loop
    await self._connect(conf)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 340, in _connect
    'Connection was re-established to Apple TV "%s"', self.atv.service.name
AttributeError: 'MrpService' object has no attribute 'name'
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[00:07:59] INFO: Using udev information from host
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-04-06 00:08:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-06 00:08:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-06 00:08:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-06 00:08:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration samsungtv_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-06 00:08:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-06 00:08:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-06 00:08:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration automower which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-06 00:08:08 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'automower'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'automower'
2021-04-06 00:09:06 ERROR (MainThread) [homeassistant.components.notify] Failed to initialize notification service ios
2021-04-06 00:09:22 ERROR (MainThread) [pyhap.characteristic] SecuritySystemCurrentState: value=0 is an invalid value.
2021-04-06 00:09:22 ERROR (MainThread) [pyhap.characteristic] SecuritySystemTargetState: value=0 is an invalid value.
2021-04-06 00:09:22 ERROR (MainThread) [pyhap.characteristic] SecuritySystemCurrentState: value=0 is an invalid value.
2021-04-06 00:09:22 ERROR (MainThread) [pyhap.characteristic] SecuritySystemTargetState: value=0 is an invalid value.
2021-04-06 00:09:22 ERROR (MainThread) [pyhap.characteristic] SecuritySystemCurrentState: value=0 is an invalid value.
2021-04-06 00:09:22 ERROR (MainThread) [pyhap.characteristic] SecuritySystemTargetState: value=0 is an invalid value.
2021-04-06 01:13:20 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1152, in _sendfile_fallback
    read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 485, in start
    resp, reset = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_fileresponse.py", line 241, in prepare
    return await self._sendfile(request, fobj, offset, count)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_fileresponse.py", line 96, in _sendfile
    await loop.sendfile(transport, fobj, offset, count)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1131, in sendfile
    return await self._sendfile_fallback(transport, file,
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1161, in _sendfile_fallback
    await proto.restore()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 263, in restore
    self._transport.resume_reading()
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 344, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
```

**Comment by agners** [comment]
It seems that the system runs out-of-memory. From the picture attached it seems that a python3 process was using a lot of memory, so that could be Home Assistant Core or the Supervisor. Do you have add-ons running? I would try disabling add-ons/integrations to isolate the component which is causing the memory issue.
