### ISSUE TITLE
Scripts don't work

### ISSUE THREAD

**Issue by andrey80nik** [home-assistant/operating-system#1419]
**Hardware Environment**

- [ ] Raspberry Pi 3

**Home Assistant OS release:**
- [ ] Fresh installation of release core-2021.6.5
- Additional information (if accessible):

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

`alias: Переключение режимов света в гостинной
sequence:
  - service: counter.increment
    data: {}
    target:
      entity_id: counter.nazhatiia
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.reset_light_level_default
  - choose:
      - conditions:
          - condition: state
            entity_id: counter.nazhatiia
            state: '1'
        sequence:
          - scene: scene.gostinnaia_srednii_svet
      - conditions:
          - condition: state
            entity_id: counter.nazhatiia
            state: '2'
        sequence:
          - scene: scene.gostinnaia_iarkii_svet
      - conditions:
          - condition: state
            entity_id: counter.nazhatiia
            state: '3'
        sequence:
          - scene: scene.gostinnaia_slabyi_svet
      - conditions:
          - condition: state
            entity_id: counter.nazhatiia
            state: '4'
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id:
                - light.yeelight_ceiling4_0x0000000007d7a28d
                - light.yeelight_ceiling4_0x0000000007d7a28d_ambilight
                - light.yeelight_ceiling4_0x0000000007d7a28d_nightlight
          - service: counter.reset
            data: {}
            entity_id: counter.nazhatiia
    default:
      - service: counter.reset
        data: {}
        entity_id: counter.nazhatiia
mode: restart
`
`alias: Сброс счетчика нажатий, для выбора  следующей схемы
sequence:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: light.yeelight_ceiling4_0x0000000007d7a28d
                state: ''
              - condition: state
                entity_id: light.yeelight_ceiling4_0x0000000007d7a28d_nightlight
                state: 'on'
              - condition: state
                entity_id: light.yeelight_ceiling4_0x0000000007d7a28d_ambilight
                state: 'on'
        sequence:
          - service: counter.configure
            data:
              value: 3
            entity_id: counter.nazhatiia
    default:
      - service: counter.reset
mode: restart
icon: mdi:restart
`
such a script used to work perfectly, but now it does not work (it does not switch scenes), so even after several runs in a row, all the scripts stop working at all, they are simply not visible in the interface and they do not work out when called indirectly.

**Comment by andrey80nik** [comment]
`2021-06-17 12:42:29 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1701065104] 'NoneType' object has no attribute 'async_turn_on'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 278, in service_handler
    await script_entity.async_turn_on(
AttributeError: 'NoneType' object has no attribute 'async_turn_on'
2021-06-17 12:42:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.roborock_vacuum_s5 is taking over 10 seconds
2021-06-17 12:42:35 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1701065104] 'NoneType' object has no attribute 'async_turn_on'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 278, in service_handler
    await script_entity.async_turn_on(
AttributeError: 'NoneType' object has no attribute 'async_turn_on'
`
