### ISSUE TITLE
Upgrading OS seems to cause issues with TubesZB zibgee coordinator

### ISSUE THREAD

**Issue by OzGav** [home-assistant/operating-system#2206]
### Describe the issue you are experiencing

I have my zigbee network working well. I have previously used a generic CC2531 stick and recently upgraded to a TubesZB CC2652. 

The last two times I have tried updating the HA OS Z2M would no longer start and I saw the message `Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'` This is when I have configured the port with either `port: /dev/serial/by-id/usb-1a86_TubesZB_971207DO-if00-port0` or `port: /dev/ttyUSB0`

If I plug my old CC2531 stick in then it works OK using `port: /dev/ttyACM0`

I just downgraded the OS back to 9.0 and it is working again. Any ideas?

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

Home Assistant OS 9.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Click on the install button for the HA OS upgrade.
2. When the system restarts Z2M does not.

### Anything in the Supervisor logs that might be useful for us?

```txt
No because I have it working again on 9.0 let me know if I need to try and upgrade it again to provide you the info you need
```

### Anything in the Host logs that might be useful for us?

```txt
No because I have it working again on 9.0 let me know if I need to try and upgrade it again to provide you the info you need
```

## System Information

version | core-2022.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Australia/Brisbane
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4874
Installed Version | 1.28.3
Stage | running
Available Repositories | 1142
Downloaded Repositories | 19

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.0
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.3.0
docker_version | 20.10.17
disk_total | 57.8 GB
disk_used | 11.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Terminal & SSH (9.6.1), Mosquitto broker (6.1.3), AdGuard Home (4.7.4), TasmoAdmin (0.20.0), Actron Air Conditioner (2022.9.2), Z-Wave JS UI (1.2.0), Zigbee2mqtt (1.22.0-3), RPC Shutdown (2.2), AirCast (3.4.1), File editor (5.4.1), ESPHome (2022.10.0), UniFi Network Application (2.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 14
views | 29
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 23, 2022 at 11:36 AM
-- | --
current_recorder_run | October 28, 2022 at 1:04 PM
estimated_db_size | 1837.33 MiB
database_engine | mysql
database_version | 10.3.32

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Additional information

Zigbee2MQTT logs

[09:31:06] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.0 start
> node index.js
Zigbee2MQTT:debug 2022-10-28 09:31:13: Loaded state from file /share/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-10-28 09:31:13: Logging to console and directory: '/share/zigbee2mqtt/log/2022-10-28.09-31-10' filename: log.txt
Zigbee2MQTT:debug 2022-10-28 09:31:13: Removing old log directory '/share/zigbee2mqtt/log/2022-10-28.09-25-20'
Zigbee2MQTT:info  2022-10-28 09:31:13: Starting Zigbee2MQTT version 1.22.0 (commit #unknown)
Zigbee2MQTT:info  2022-10-28 09:31:13: Starting zigbee-herdsman (0.13.164)
Zigbee2MQTT:debug 2022-10-28 09:31:13: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[26],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/serial/by-id/usb-1a86_TubesZB_971207DO-if00-port0"}}'
Zigbee2MQTT:error 2022-10-28 09:31:13: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-10-28 09:31:13: Failed to start zigbee
Zigbee2MQTT:error 2022-10-28 09:31:13: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2022-10-28 09:31:13: Exiting...
Zigbee2MQTT:error 2022-10-28 09:31:13: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[09:31:14] INFO: Handing over control to Zigbee2mqtt Core ...

**Comment by OzGav** [comment]
Actually still an issue on 9.0 so not sure it is a OS problem. Will investigate further.
