### ISSUE TITLE
HA gets offline in the night

### ISSUE THREAD

**Issue by csoltenborn** [home-assistant/operating-system#2231]
### Describe the issue you are experiencing

Quite frequently my HA instance is not accessible in the morning. I' running HA OS within a VM on a Ubuntu server, and this morning I captured a screenshot of the VM screen. Does that error message mean anything to you? Is this a HA OS bug, or is there anything I can do to avoid that problem?

![S9YIPP~H](https://user-images.githubusercontent.com/352576/201865855-4c938999-93f8-48e5-bd80-0367dcee5061.PNG)

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

9.3

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

As far as I can tell, this "just happens" during the night...

### Anything in the Supervisor logs that might be useful for us?

```txt
Not sure whether this is helpful (that's all there is):


22-11-15 09:07:12 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
[08:11:35] INFO: Watchdog restart after closing
[08:11:35] INFO: Starting local supervisor watchdog...
22-11-15 09:11:55 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1378, in _create_connection
    _, proto = await self._loop.create_unix_connection(
  File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 254, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 505, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 126, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 56, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 116, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 138, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 204, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 60, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/host.py", line 189, in advanced_logs
    async with self.sys_host.logs.journald_logs(
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/src/supervisor/supervisor/host/logs.py", line 148, in journald_logs
    async with session.get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1384, in _create_connection
    raise UnixClientConnectorError(self.path, req.connection_key, exc) from exc
aiohttp.client_exceptions.UnixClientConnectorError: Cannot connect to unix socket /run/systemd-journal-gatewayd.sock ssl:default [Connection refused]
22-11-15 09:12:02 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1378, in _create_connection
    _, proto = await self._loop.create_unix_connection(
  File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 254, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 505, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 126, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 56, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 116, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 138, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 204, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 60, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/host.py", line 189, in advanced_logs
    async with self.sys_host.logs.journald_logs(
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/src/supervisor/supervisor/host/logs.py", line 148, in journald_logs
    async with session.get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1384, in _create_connection
    raise UnixClientConnectorError(self.path, req.connection_key, exc) from exc
aiohttp.client_exceptions.UnixClientConnectorError: Cannot connect to unix socket /run/systemd-journal-gatewayd.sock ssl:default [Connection refused]
```
```


### Anything in the Host logs that might be useful for us?

```txt
Trying to access the host logs results in an error: `500 Internal Server Error Server got itself in trouble`
```

## System Information

version | core-2022.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.74
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4920
Installed Version | 1.28.3
Stage | running
Available Repositories | 1135
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 30.8 GB
disk_used | 10.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.4.2), Duck DNS (1.15.0), Terminal & SSH (9.6.1), Samba Backup (5.0.0), Studio Code Server (5.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 7
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9. November 2022 um 03:12
-- | --
current_recorder_run | 15. November 2022 um 09:06
estimated_db_size | 89.10 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by agners** [comment]
This could be memory related. How much memory do you have, and how much of it is in use by default?
