### ISSUE TITLE
3 home assistant systems on different pc's won't update anything

### ISSUE THREAD

**Issue by malosaa** [home-assistant/operating-system#2232]
### Describe the issue you are experiencing

all 3 hass servers are on virtualbox windows

I did see on all systems that the new supervisor was available, together with a couple of add-ons.
When pressing to update first fupervisor on all 3 systems it keeps loading for ages.

So i restarted all 3 systems, only 2 did restart 1 blocked and said somthing about a start state in the terminal, so i manually rebooted it.

After the reboot i just wanted to update the add-ons, same issue on all 3 systems it keeps loading for aged.

I can ping to 1.1.1.1 and 1.0.0.1 all good, also internet is good.
Also my system is heathy.

Here is a log of one of them, yes this is the only one running core-2022.11.0b1, the other 2 are on the last version.

this is happening on all 3 different servers with the same issue.

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

Home Assistant OS 9.3

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

just pressing update

### Anything in the Supervisor logs that might be useful for us?

```txt
22-11-15 09:02:35 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'db21ed7f_portainer', 'hassio-supervisor'}
22-11-15 09:02:35 INFO (MainThread) [supervisor.docker.monitor] Started docker events monitor
22-11-15 09:02:35 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/amd64-hassio-cli with version 2022.11.0
22-11-15 09:02:36 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/amd64-hassio-dns with version 2022.04.1
22-11-15 09:02:36 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
22-11-15 09:02:36 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/amd64-hassio-audio with version 2022.07.0
22-11-15 09:02:36 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/amd64-hassio-observer with version 2022.10.0
22-11-15 09:02:36 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/amd64-hassio-multicast with version 2022.02.0
22-11-15 09:02:36 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json
22-11-15 09:02:38 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/qemux86-64-homeassistant with version 2022.11.0b1
22-11-15 09:02:38 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 1 Home Assistant secrets
22-11-15 09:02:38 INFO (MainThread) [supervisor.os.manager] Detect Home Assistant Operating System 9.3 / BootSlot A
22-11-15 09:02:41 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
22-11-15 09:02:41 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/db21ed7f repository
22-11-15 09:02:41 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
22-11-15 09:02:41 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/5c53de3b repository
22-11-15 09:02:47 INFO (MainThread) [supervisor.store] Loading add-ons from store: 138 all - 138 new - 0 remove
22-11-15 09:02:47 INFO (MainThread) [supervisor.addons] Found 3 installed add-ons
22-11-15 09:02:47 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-configurator with version 5.4.1
22-11-15 09:02:47 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to db21ed7f/amd64-addon-portainer with version 2.15.1
22-11-15 09:02:47 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/ssh/amd64 with version 12.0.2
22-11-15 09:02:47 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files
22-11-15 09:02:47 INFO (MainThread) [supervisor.discovery] Loaded 0 messages
22-11-15 09:02:47 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
22-11-15 09:02:47 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
22-11-15 09:02:47 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-11-15 09:02:47 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
22-11-15 09:02:47 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-15 09:02:47 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.SETUP
22-11-15 09:02:47 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
22-11-15 09:02:47 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-15 09:02:47 INFO (MainThread) [__main__] Running Supervisor
TypeError: Expected unicode, got RaucState
Exception ignored in: 'dbus_fast._private.marshaller.Marshaller._write_single'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 103, in buffer_message
    msg._marshall(self.negotiate_unix_fd),
TypeError: Expected unicode, got RaucState
22-11-15 09:02:47 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/os/manager.py", line 232, in mark_healthy
    response = await self.sys_dbus.rauc.mark(RaucState.GOOD, "booted")
  File "/usr/src/supervisor/supervisor/dbus/rauc.py", line 98, in mark
    return await self.dbus.Installer.call_mark(state, slot_identifier)
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 100, in call_dbus
    return await getattr(proxy_interface, method)(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/proxy_object.py", line 90, in method_fn
    msg = await self.bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 370, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 24, in dbus_fast.aio.message_reader.build_message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 641, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 524, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 276, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
EOFError
22-11-15 09:02:47 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-229' coro=<Core.start() done, defined at /usr/src/supervisor/supervisor/core.py:171> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/os/manager.py", line 232, in mark_healthy
    response = await self.sys_dbus.rauc.mark(RaucState.GOOD, "booted")
  File "/usr/src/supervisor/supervisor/dbus/rauc.py", line 98, in mark
    return await self.dbus.Installer.call_mark(state, slot_identifier)
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 100, in call_dbus
    return await getattr(proxy_interface, method)(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/proxy_object.py", line 90, in method_fn
    msg = await self.bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 370, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 24, in dbus_fast.aio.message_reader.build_message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 641, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 524, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 276, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
EOFError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/core.py", line 184, in start
    await self.sys_os.mark_healthy()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 160, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
22-11-16 00:17:31 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-11-16 00:17:31 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/alexbelgium/hassio-addons repository
22-11-16 00:17:31 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-11-16 00:17:31 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-11-16 00:17:32 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json
22-11-16 00:17:34 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-11-16 00:17:40 INFO (MainThread) [supervisor.store] Loading add-ons from store: 138 all - 0 new - 0 remove
22-11-16 00:17:40 INFO (MainThread) [supervisor.store] Loading add-ons from store: 138 all - 0 new - 0 remove
22-11-16 00:21:11 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files
22-11-16 00:21:11 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files
22-11-16 07:58:11 INFO (SyncWorker_1) [supervisor.docker.manager] Runing command 'python3 -m homeassistant -c /config --script check_config' on ghcr.io/home-assistant/qemux86-64-homeassistant
22-11-16 08:07:54 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant config is valid
22-11-16 08:16:50 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor.txt
22-11-16 08:16:54 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
```

### Anything in the Host logs that might be useful for us?

```txt
no
```

## System Information

version | core-2022.11.0b1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.74
arch | x86_64
timezone | UTC
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4893
Installed Version | 1.28.3
Stage | running
Available Repositories | 1142
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | beta
supervisor_version | supervisor-2022.11.0
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 30.8 GB
disk_used | 8.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (12.0.2), Portainer (2.15.1), File editor (5.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 8, 2022 at 1:13 PM
-- | --
current_recorder_run | November 15, 2022 at 9:01 AM
estimated_db_size | 4.20 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by malosaa** [comment]
![image](https://user-images.githubusercontent.com/13116501/202124907-e053dbd7-64a7-4587-8917-343bcf5bc4b4.png)

and when try to create backup it says the system is in start up state

**Comment by malosaa** [comment]
i did a host restart and here is the log,

```txt
22-11-16 09:15:14 WARNING (SyncWorker_1) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Google Assistant Webserver
22-11-16 09:15:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/fe49a976 repository
22-11-16 09:15:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/db21ed7f repository
22-11-16 09:15:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/5c53de3b repository
22-11-16 09:15:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
22-11-16 09:15:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/ccab4aaf repository
22-11-16 09:15:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/734f8bef repository
22-11-16 09:15:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/15d21743 repository
22-11-16 09:15:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
22-11-16 09:15:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/45df7312 repository
22-11-16 09:15:18 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/6a3d001f repository
22-11-16 09:15:26 WARNING (SyncWorker_3) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Google Assistant Webserver
22-11-16 09:15:28 INFO (MainThread) [supervisor.store] Loading add-ons from store: 153 all - 153 new - 0 remove
22-11-16 09:15:28 INFO (MainThread) [supervisor.addons] Found 16 installed add-ons
22-11-16 09:15:28 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/ssh/amd64 with version 12.0.2
22-11-16 09:15:28 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/phpmyadmin/amd64 with version 0.8.2
22-11-16 09:15:28 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/tor/amd64 with version 4.0.2
22-11-16 09:15:28 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-ssh with version 9.6.1
22-11-16 09:15:28 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to blakeblackshear/frigate with version 0.11.0-rc2
22-11-16 09:15:28 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-configurator with version 5.4.2
22-11-16 09:15:28 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-mosquitto with version 6.1.3
22-11-16 09:15:28 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-mariadb with version 2.5.1
22-11-16 09:15:28 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/node-red/amd64 with version 13.5.2
22-11-16 09:15:28 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-duckdns with version 1.15.0
22-11-16 09:15:28 INFO (SyncWorker_4) [supervisor.docker.interface] Attaching to db21ed7f/amd64-addon-portainer with version 2.15.1
22-11-16 09:15:28 INFO (SyncWorker_1) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/vscode/amd64 with version 5.4.1
22-11-16 09:15:28 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to andbobsyouruncle/amd64-google-assistant-webserver with version 0.0.4
22-11-16 09:15:28 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-samba with version 10.0.0
22-11-16 09:15:28 INFO (SyncWorker_5) [supervisor.docker.interface] Attaching to zigbee2mqtt/zigbee2mqtt-edge-amd64 with version edge
22-11-16 09:15:28 INFO (MainThread) [supervisor.backups.manager] Found 36 backup files
22-11-16 09:15:29 INFO (MainThread) [supervisor.discovery] Loaded 1 messages
22-11-16 09:15:29 INFO (MainThread) [supervisor.ingress] Loaded 3 ingress sessions
22-11-16 09:15:29 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
22-11-16 09:15:29 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-11-16 09:15:29 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
22-11-16 09:15:29 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-16 09:15:29 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.SETUP
22-11-16 09:15:29 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
22-11-16 09:15:29 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-16 09:15:29 INFO (MainThread) [__main__] Running Supervisor
TypeError: Expected unicode, got RaucState
Exception ignored in: 'dbus_fast._private.marshaller.Marshaller._write_single'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 103, in buffer_message
    msg._marshall(self.negotiate_unix_fd),
TypeError: Expected unicode, got RaucState
22-11-16 09:15:29 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/os/manager.py", line 232, in mark_healthy
    response = await self.sys_dbus.rauc.mark(RaucState.GOOD, "booted")
  File "/usr/src/supervisor/supervisor/dbus/rauc.py", line 98, in mark
    return await self.dbus.Installer.call_mark(state, slot_identifier)
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 100, in call_dbus
    return await getattr(proxy_interface, method)(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/proxy_object.py", line 90, in method_fn
    msg = await self.bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 370, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 24, in dbus_fast.aio.message_reader.build_message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 641, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 524, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 276, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
EOFError
22-11-16 09:15:29 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-689' coro=<Core.start() done, defined at /usr/src/supervisor/supervisor/core.py:171> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/os/manager.py", line 232, in mark_healthy
    response = await self.sys_dbus.rauc.mark(RaucState.GOOD, "booted")
  File "/usr/src/supervisor/supervisor/dbus/rauc.py", line 98, in mark
    return await self.dbus.Installer.call_mark(state, slot_identifier)
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 100, in call_dbus
    return await getattr(proxy_interface, method)(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/proxy_object.py", line 90, in method_fn
    msg = await self.bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 370, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 24, in dbus_fast.aio.message_reader.build_message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 641, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 524, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 276, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
EOFError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/core.py", line 184, in start
    await self.sys_os.mark_healthy()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 160, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
22-11-16 09:15:44 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-11-16 09:15:45 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.STARTUP
22-11-16 09:15:45 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-16 09:15:49 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json
22-11-16 09:15:49 WARNING (MainThread) [supervisor.jobs] 'StoreManager.reload' blocked from execution, supervisor needs to be updated first
22-11-16 09:17:40 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
```

**Comment by malosaa** [comment]
i do see all 3 have this error in the supervisor logs.
I really did not touch any of them, or modificate a server or setting.
This happened when the new supervisor update came after pressing the update button, i did do this on all 3 of them.

`TypeError: Expected unicode, got RaucState`
