### ISSUE TITLE
Home Assistant Crashes on Restart, not on Reboot.

### ISSUE THREAD

**Issue by spartandrew18** [home-assistant/operating-system#2321]
### Describe the issue you are experiencing

On Restart of Home Assistant my system will crash on startup. It does not occur on Rebooting system, only on Restarting.

### What operating system image do you use?

yellow (Home Assistant Yellow)

### What version of Home Assistant Operating System is installed?

9.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.Settings
2.System
3.Restart
4.Startup
5.Crash

### Anything in the Supervisor logs that might be useful for us?

```txt
2023-01-26 17:24:01.141 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration tplink_deco which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-26 17:24:01.143 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-26 17:24:01.145 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration vesync_formatbce which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-26 17:24:01.147 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-26 17:24:25.083 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for hacs using this method at custom_components/hacs/__init__.py, line 177: hass.config_entries.async_setup_platforms(
2023-01-26 17:24:26.154 ERROR (bellows.thread_0) [bellows.uart] Lost serial connection: OSError('Server closed connection')
2023-01-26 17:24:27.678 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:27.750 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:27.962 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:28.072 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:28.484 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:28.547 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:28.956 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:29.335 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:30.159 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:30.243 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:30.391 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:31.131 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:31.336 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:31.652 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:31.850 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:33.112 WARNING (MainThread) [aiohomekit.controller.coap.connection] Pair verify timed out
2023-01-26 17:24:33.116 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Nanoleaf A19 699D' for homekit_controller integration not ready yet: failed to connect; Retrying in background
2023-01-26 17:24:33.771 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:34.407 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:34.960 WARNING (MainThread) [aiohomekit.controller.coap.pdu] Transaction 0 failed with error 6 (Invalid request
2023-01-26 17:24:35.258 WARNING (Recorder) [homeassistant.components.recorder.core] Recorder startup was externally canceled before it could complete: 
2023-01-26 17:24:35.348 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 111, in async_setup_entry
    await zha_gateway.async_initialize()
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 174, in async_initialize
    self.application_controller = await app_controller_cls.new(
  File "/usr/local/lib/python3.10/site-packages/zigpy/application.py", line 169, in new
    await app.startup(auto_form=auto_form)
  File "/usr/local/lib/python3.10/site-packages/zigpy/application.py", line 145, in startup
    await self.connect()
  File "/usr/local/lib/python3.10/site-packages/bellows/zigbee/application.py", line 124, in connect
    self._ezsp = await bellows.ezsp.EZSP.initialize(self.config)
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 104, in initialize
    await ezsp._startup_reset()
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 84, in _startup_reset
    await asyncio.wait_for(
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 295, in _async_setup_component
    await asyncio.gather(
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 100, in async_setup_component
    return await task
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/runner.py", line 109, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 151, in async_setup_hass
    await async_from_config_dict(config_dict, hass) is not None
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 291, in async_from_config_dict
    await _async_set_up_integrations(hass, config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 647, in _async_set_up_integrations
    await async_setup_multi_components(hass, stage_2_domains, config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 514, in async_setup_multi_components
    errors = [domain for domain in domains if futures[domain].exception()]
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 514, in <listcomp>
    errors = [domain for domain in domains if futures[domain].exception()]
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 226, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 214, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 128, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
2023-01-26 17:24:55.351 ERROR (Thread-3) [pychromecast.discovery] Unhandled exception in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pychromecast/discovery.py", line 302, in run
    self._poll_hosts()
  File "/usr/local/lib/python3.10/site-packages/pychromecast/discovery.py", line 393, in _poll_hosts
    self._update_devices(host, devices, uuids)
  File "/usr/local/lib/python3.10/site-packages/pychromecast/discovery.py", line 430, in _update_devices
    callback()
  File "/usr/src/homeassistant/homeassistant/components/cast/discovery.py", line 68, in update_cast
    discover_chromecast(hass, browser.devices[uuid])
  File "/usr/src/homeassistant/homeassistant/components/cast/discovery.py", line 40, in discover_chromecast
    dispatcher_send(hass, SIGNAL_CAST_DISCOVERED, info)
  File "/usr/src/homeassistant/homeassistant/helpers/dispatcher.py", line 62, in dispatcher_send
    hass.loop.call_soon_threadsafe(async_dispatcher_send, hass, signal, *args)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 795, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2023-01-26 17:24:55.364 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/pychromecast/discovery.py", line 302, in run
    self._poll_hosts()
  File "/usr/local/lib/python3.10/site-packages/pychromecast/discovery.py", line 393, in _poll_hosts
    self._update_devices(host, devices, uuids)
  File "/usr/local/lib/python3.10/site-packages/pychromecast/discovery.py", line 430, in _update_devices
    callback()
  File "/usr/src/homeassistant/homeassistant/components/cast/discovery.py", line 68, in update_cast
    discover_chromecast(hass, browser.devices[uuid])
  File "/usr/src/homeassistant/homeassistant/components/cast/discovery.py", line 40, in discover_chromecast
    dispatcher_send(hass, SIGNAL_CAST_DISCOVERED, info)
  File "/usr/src/homeassistant/homeassistant/helpers/dispatcher.py", line 62, in dispatcher_send
    hass.loop.call_soon_threadsafe(async_dispatcher_send, hass, signal, *args)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 795, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

### Anything in the Host logs that might be useful for us?

```txt
Could Not get.
```

**Comment by agners** [comment]
This turned out not to be an issue related to HAOS 9.5 (it was reproducible with HAOS 9.4 as well). More details are in this issue: https://github.com/home-assistant/core/issues/86800.
