### ISSUE TITLE
 Error: Unable to create websockets listener on port 1884

### ISSUE THREAD

**Issue by jbouwh** [home-assistant/operating-system#2428]
### Describe the issue you are experiencing

The Mosquitto broker add does not start any ,ore after upgrading to OS to 

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.0.rc1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Upgrade to OS to 10.0.rc1
2. Disable port 1884 in the addon
3. Restart the addon
...
See log the addon fails to start up. Before the upgrade it ran okay.

### Anything in the Supervisor logs that might be useful for us?

```txt
23-03-25 11:52:23 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 11:52:23 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 11:52:25 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.1.3
23-03-25 11:52:42 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2289' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:989> exception=AddonsJobError('Rate limit exceeded, more then 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1003, in watchdog_container
    await self._restart_after_problem(self, event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 144, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more then 10 calls in 0:30:00
23-03-25 11:52:50 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-03-25 11:52:50 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_appdaemon
23-03-25 11:52:50 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-03-25 11:55:13 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-03-25 12:00:16 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-03-25 12:05:19 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-03-25 12:06:15 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-03-25 12:10:22 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-03-25 12:15:25 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-03-25 12:20:28 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-03-25 12:21:36 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-03-25 12:23:59 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 12:23:59 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 12:24:01 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.1.3
23-03-25 12:24:16 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 12:24:16 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 12:24:17 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.1.3
23-03-25 12:24:33 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 12:24:33 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 12:24:34 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.1.3
```

### Anything in the Host logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py", line 436, in async_publish_service
    await mqtt_data.client.async_publish(msg_topic, payload, qos, retain)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 407, in async_publish
    _raise_on_error(msg_info.rc)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 823, in _raise_on_error
    _raise_on_errors((result_code,))
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 818, in _raise_on_errors
    raise HomeAssistantError(f"Error talking to MQTT: {', '.join(messages)}")
homeassistant.exceptions.HomeAssistantError: Error talking to MQTT: The client is not currently connected.
```

## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.13-v8
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.31.0
Stage | running
Available Repositories | 1312
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0.rc1
-- | --
update_channel | beta
supervisor_version | supervisor-2023.03.2
agent_version | 1.5.1
docker_version | 23.0.1
disk_total | 57.6 GB
disk_used | 30.1 GB
healthy | true
supported | failed to load: Unsupported
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), AppDaemon (0.11.0), File editor (5.5.0), Mosquitto broker (6.1.3), Grafana (8.2.0), InfluxDB (4.5.0), Studio Code Server (5.5.4), Portainer (2.17.1-9), MariaDB (2.5.2), Silicon Labs Multiprotocol (1.0.2), Matter Server (4.1.0), ESPHome (2023.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23 februari 2023 om 05:37
-- | --
current_recorder_run | 25 maart 2023 om 11:49
estimated_db_size | 5196.36 MiB
database_engine | mysql
database_version | 10.10.2

</details>

### Additional information

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[12:35:20] INFO: Setting up user xxxxx
[12:35:21] INFO: Setting up user xxxxx
[12:35:22] INFO: Setting up user xxxxx
[12:35:23] INFO: Setting up user xxxxx
[12:35:24] INFO: Setting up user xxxxx
[12:35:25] INFO: SSL is not enabled
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[12:35:26] INFO: Starting NGINX for authentication handling...
[12:35:27] INFO: Starting mosquitto MQTT broker...
2023-03-25 12:35:27: Warning: Mosquitto should not be run as root/administrator.
2023-03-25 12:35:27: mosquitto version 2.0.11 starting
2023-03-25 12:35:27: Config loaded from /etc/mosquitto/mosquitto.conf.
2023-03-25 12:35:27: Loading plugin: /usr/share/mosquitto/go-auth.so
2023-03-25 12:35:27:  ├── Username/password checking enabled.
2023-03-25 12:35:27:  ├── TLS-PSK checking enabled.
2023-03-25 12:35:27:  └── Extended authentication not enabled.
2023-03-25 12:35:27: Opening ipv4 listen socket on port 1883.
2023-03-25 12:35:27: Opening ipv6 listen socket on port 1883.
2023-03-25 12:35:27: Opening websockets listen socket on port 1884.
2023-03-25 12:35:27: Error: Unable to create websockets listener on port 1884.
[11:35:27] WARNING: Halt add-on
s6-rc: info: service legacy-services: stopping
[11:35:27] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by owenmcarthur** [comment]
same problem over here after update.

**Comment by agners** [comment]
The culprit seems to be an issue in libwebsockets, and is resolved in newer versions of it, see also https://github.com/home-assistant/addons/issues/2904. There is PR which is fixing this, see https://github.com/home-assistant/addons/pull/2923.

Once Mosquitto add-on has been updated, this should be resolved.

**Comment by krobit** [comment]
same problem

**Comment by gregdeux** [comment]
same

**Comment by angaro142** [comment]
Same

**Comment by airsailor** [comment]
Same here. This is terrible because 90% of my HA work by mqtt. Now I have nothing. Please someone solve this problem

**Comment by agners** [comment]
This is solved with the latest add-on 6.2.0.
