### ISSUE TITLE
Missing addons repositories 

### ISSUE THREAD

**Issue by SlimPugGamer** [home-assistant/operating-system#2497]
### Describe the issue you are experiencing

Missing addon repositories 

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

10.0

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Install home assistant os from raspberry pi imager
2. Setup home assistant 
3. Go to addons

### Anything in the Supervisor logs that might be useful for us?

```txt
23-04-21 17:30:20 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ghcr.io/esphome/esphome-hassio with version 2023.4.0
23-04-21 17:30:20 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_a0d7b954_uptime-kuma application
23-04-21 17:30:23 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/uptime-kuma/aarch64 with version 0.7.2
23-04-21 17:30:28 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
23-04-21 17:30:28 INFO (MainThread) [supervisor.core] Supervisor is up and running
23-04-21 17:30:28 INFO (MainThread) [supervisor.host.info] Updating local host information
23-04-21 17:30:28 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-04-21 17:30:28 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-04-21 17:30:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-04-21 17:30:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-04-21 17:30:29 INFO (MainThread) [supervisor.host.services] Updating service information
23-04-21 17:30:29 INFO (MainThread) [supervisor.host.network] Updating local network information
23-04-21 17:30:29 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-04-21 17:30:29 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.MULTIPLE_DATA_DISKS/ContextType.SYSTEM
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.CREATE_FULL_BACKUP - ContextType.SYSTEM / None
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.NO_CURRENT_BACKUP - ContextType.SYSTEM / None
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-04-21 17:30:31 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-04-21 17:53:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-04-21 17:53:34 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons
23-04-21 17:53:39 INFO (MainThread) [supervisor.store] Loading add-ons from store: 40 all - 0 new - 0 remove
23-04-21 17:53:39 INFO (MainThread) [supervisor.store] Loading add-ons from store: 40 all - 0 new - 0 remove
23-04-21 17:54:44 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/esphome/hassio repository
23-04-21 17:54:46 INFO (MainThread) [supervisor.store] Loading add-ons from store: 43 all - 3 new - 0 remove
23-04-21 17:55:12 ERROR (MainThread) [supervisor.store] Can't add https://github.com/hassio-addons/repository, already in the store
23-04-21 17:55:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-04-21 17:55:24 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons
23-04-21 17:55:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/hassio repository
23-04-21 17:55:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 102, in wrap_api
    msg_data = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/store.py", line 248, in addons_addon_changelog
    if not addon.with_changelog:
  File "/usr/src/supervisor/supervisor/addons/model.py", line 499, in with_changelog
    return self.path_changelog.exists()
  File "/usr/src/supervisor/supervisor/addons/model.py", line 564, in path_changelog
    return Path(self.path_location, "CHANGELOG.md")
  File "/usr/src/supervisor/supervisor/addons/model.py", line 549, in path_location
    return Path(self.data[ATTR_LOCATON])
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
KeyError: 'a0d7b954_zwavejs2mqtt'
23-04-21 17:55:26 INFO (MainThread) [supervisor.store] Loading add-ons from store: 43 all - 0 new - 0 remove
23-04-21 17:55:26 INFO (MainThread) [supervisor.store] Loading add-ons from store: 43 all - 0 new - 0 remove
23-04-21 17:55:34 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-04-21 17:55:34 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/hassio repository
23-04-21 17:55:34 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons
23-04-21 17:55:36 INFO (MainThread) [supervisor.store] Loading add-ons from store: 43 all - 0 new - 0 remove
23-04-21 17:55:36 INFO (MainThread) [supervisor.store] Loading add-ons from store: 43 all - 0 new - 0 remove
23-04-21 17:56:09 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-04-21 17:56:09 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/hassio repository
23-04-21 17:56:09 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons
23-04-21 17:56:09 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-04-21 17:56:11 INFO (MainThread) [supervisor.store] Loading add-ons from store: 43 all - 0 new - 0 remove
23-04-21 17:56:11 INFO (MainThread) [supervisor.store] Loading add-ons from store: 43 all - 0 new - 0 remove
23-04-21 17:56:26 INFO (SyncWorker_0) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-64-homeassistant
23-04-21 17:56:36 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-04-21 17:56:42 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-04-21 17:56:42 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-04-21 17:56:43 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-04-21 17:56:43 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/hassio repository
23-04-21 17:56:43 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-04-21 17:56:43 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons
23-04-21 17:56:45 INFO (MainThread) [supervisor.store] Loading add-ons from store: 43 all - 0 new - 0 remove
23-04-21 17:56:45 INFO (MainThread) [supervisor.store] Loading add-ons from store: 43 all - 0 new - 0 remove
23-04-21 17:57:01 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-04-21 18:00:28 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```

### Anything in the Host logs that might be useful for us?

```txt
Apr 21 14:29:48 homeassistant kernel: audit: type=1327 audit(1682087388.039:181): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F64386134626338386362366131353036396435383466346165
Apr 21 14:29:48 homeassistant kernel: audit: type=1334 audit(1682087388.039:182): prog-id=43 op=LOAD
Apr 21 14:29:48 homeassistant kernel: audit: type=1300 audit(1682087388.039:182): arch=c00000b7 syscall=280 success=yes exit=17 a0=5 a1=4000137490 a2=78 a3=0 items=0 ppid=2764 pid=2775 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Apr 21 14:29:48 homeassistant kernel: audit: type=1327 audit(1682087388.039:182): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F64386134626338386362366131353036396435383466346165
Apr 21 14:29:48 homeassistant kernel: audit: type=1334 audit(1682087388.043:183): prog-id=43 op=UNLOAD
Apr 21 14:29:48 homeassistant kernel: audit: type=1334 audit(1682087388.043:184): prog-id=42 op=UNLOAD
Apr 21 14:29:48 homeassistant kernel: audit: type=1334 audit(1682087388.043:185): prog-id=44 op=LOAD
Apr 21 14:29:48 homeassistant kernel: audit: type=1300 audit(1682087388.043:185): arch=c00000b7 syscall=280 success=yes exit=15 a0=5 a1=4000137960 a2=78 a3=0 items=0 ppid=2764 pid=2775 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Apr 21 14:29:48 homeassistant dockerd[537]: time="2023-04-21T14:29:48.673045088Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;github.com.\tIN\t AAAA" error="read udp 172.30.232.2:34523->192.168.1.1:53: i/o timeout"
Apr 21 14:29:48 homeassistant dockerd[537]: time="2023-04-21T14:29:48.674219996Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;github.com.\tIN\t AAAA" error="read udp 172.30.232.2:41019->192.168.1.1:53: i/o timeout"
Apr 21 14:29:55 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Apr 21 14:29:55 homeassistant kernel: kauditd_printk_skb: 1 callbacks suppressed
Apr 21 14:29:55 homeassistant kernel: audit: type=1334 audit(1682087395.684:186): prog-id=14 op=UNLOAD
Apr 21 14:29:55 homeassistant kernel: audit: type=1334 audit(1682087395.684:187): prog-id=13 op=UNLOAD
Apr 21 14:29:55 homeassistant kernel: audit: type=1334 audit(1682087395.684:188): prog-id=12 op=UNLOAD
Apr 21 14:29:55 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Apr 21 14:29:55 homeassistant kernel: audit: type=1334 audit(1682087395.960:189): prog-id=25 op=UNLOAD
Apr 21 14:29:55 homeassistant kernel: audit: type=1334 audit(1682087395.960:190): prog-id=24 op=UNLOAD
Apr 21 14:29:55 homeassistant kernel: audit: type=1334 audit(1682087395.960:191): prog-id=23 op=UNLOAD
Apr 21 14:30:19 homeassistant systemd[1]: var-lib-docker-overlay2-495c1e6f4aae58959d45f81f7168b3b32bdb1cb0c9866ac2f80cd2c6aff217df\x2dinit-merged.mount: Deactivated successfully.
Apr 21 14:30:19 homeassistant systemd[1]: mnt-data-docker-overlay2-495c1e6f4aae58959d45f81f7168b3b32bdb1cb0c9866ac2f80cd2c6aff217df\x2dinit-merged.mount: Deactivated successfully.
Apr 21 14:30:20 homeassistant systemd[1]: Started libcontainer container ff6f05943802409c3e4e79e100aec6d04116f6d9a41cab51758163eabb29ae46.
Apr 21 14:30:20 homeassistant kernel: audit: type=1334 audit(1682087420.424:192): prog-id=45 op=LOAD
Apr 21 14:30:20 homeassistant kernel: audit: type=1334 audit(1682087420.424:193): prog-id=46 op=LOAD
Apr 21 14:30:20 homeassistant kernel: audit: type=1300 audit(1682087420.424:193): arch=c00000b7 syscall=280 success=yes exit=15 a0=5 a1=400018d700 a2=78 a3=0 items=0 ppid=3006 pid=3016 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Apr 21 14:30:20 homeassistant kernel: audit: type=1327 audit(1682087420.424:193): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F66663666303539343338303234303963336534653739653130
Apr 21 14:30:20 homeassistant kernel: audit: type=1334 audit(1682087420.424:194): prog-id=47 op=LOAD
Apr 21 14:30:20 homeassistant kernel: audit: type=1300 audit(1682087420.424:194): arch=c00000b7 syscall=280 success=yes exit=17 a0=5 a1=400018d490 a2=78 a3=0 items=0 ppid=3006 pid=3016 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Apr 21 14:30:20 homeassistant kernel: audit: type=1327 audit(1682087420.424:194): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F66663666303539343338303234303963336534653739653130
Apr 21 14:30:20 homeassistant kernel: audit: type=1334 audit(1682087420.424:195): prog-id=47 op=UNLOAD
Apr 21 14:30:20 homeassistant kernel: audit: type=1334 audit(1682087420.424:196): prog-id=46 op=UNLOAD
Apr 21 14:30:20 homeassistant kernel: audit: type=1334 audit(1682087420.424:197): prog-id=48 op=LOAD
Apr 21 14:30:20 homeassistant systemd[1]: var-lib-docker-overlay2-5b24d91145804929b5fbb134f57cd8db55966caec6c7c0e1e6fa7748964f4d8e\x2dinit-merged.mount: Deactivated successfully.
Apr 21 14:30:20 homeassistant systemd[1]: mnt-data-docker-overlay2-5b24d91145804929b5fbb134f57cd8db55966caec6c7c0e1e6fa7748964f4d8e\x2dinit-merged.mount: Deactivated successfully.
Apr 21 14:30:21 homeassistant kernel: hassio: port 6(veth0158d10) entered blocking state
Apr 21 14:30:21 homeassistant kernel: hassio: port 6(veth0158d10) entered disabled state
Apr 21 14:30:21 homeassistant kernel: device veth0158d10 entered promiscuous mode
Apr 21 14:30:21 homeassistant NetworkManager[427]: <info>  [1682087421.6671] manager: (vethe691bd8): new Veth device (/org/freedesktop/NetworkManager/Devices/19)
Apr 21 14:30:21 homeassistant NetworkManager[427]: <info>  [1682087421.6716] manager: (veth0158d10): new Veth device (/org/freedesktop/NetworkManager/Devices/20)
Apr 21 14:30:22 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-01f925257a4588793f52547a572e641c03cdea747221aab58e55aa678ce4a7a6-runc.uO2rDX.mount: Deactivated successfully.
Apr 21 14:30:22 homeassistant systemd[1]: Started libcontainer container 01f925257a4588793f52547a572e641c03cdea747221aab58e55aa678ce4a7a6.
Apr 21 14:30:22 homeassistant kernel: eth0: renamed from vethe691bd8
Apr 21 14:30:22 homeassistant kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth0158d10: link becomes ready
Apr 21 14:30:22 homeassistant kernel: hassio: port 6(veth0158d10) entered blocking state
Apr 21 14:30:22 homeassistant kernel: hassio: port 6(veth0158d10) entered forwarding state
Apr 21 14:30:22 homeassistant NetworkManager[427]: <info>  [1682087422.8514] device (veth0158d10): carrier: link connected
Apr 21 14:30:28 homeassistant kernel: kauditd_printk_skb: 50 callbacks suppressed
Apr 21 14:30:28 homeassistant kernel: audit: type=1334 audit(1682087428.117:216): prog-id=53 op=LOAD
Apr 21 14:30:28 homeassistant kernel: audit: type=1334 audit(1682087428.121:217): prog-id=54 op=LOAD
Apr 21 14:30:28 homeassistant kernel: audit: type=1334 audit(1682087428.121:218): prog-id=55 op=LOAD
Apr 21 14:30:28 homeassistant systemd[1]: Starting Hostname Service...
Apr 21 14:30:28 homeassistant systemd[1]: Started Hostname Service.
Apr 21 14:30:28 homeassistant kernel: audit: type=1334 audit(1682087428.631:219): prog-id=56 op=LOAD
Apr 21 14:30:28 homeassistant kernel: audit: type=1334 audit(1682087428.635:220): prog-id=57 op=LOAD
Apr 21 14:30:28 homeassistant kernel: audit: type=1334 audit(1682087428.635:221): prog-id=58 op=LOAD
Apr 21 14:30:28 homeassistant systemd[1]: Starting Time & Date Service...
Apr 21 14:30:28 homeassistant systemd[1]: Started Time & Date Service.
Apr 21 14:30:32 homeassistant dockerd[537]: time="2023-04-21T14:30:32.109153511Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;version.home-assistant.io.\tIN\t A" error="read udp 172.30.232.2:37438->192.168.1.1:53: i/o timeout"
Apr 21 14:30:58 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Apr 21 14:30:58 homeassistant kernel: audit: type=1334 audit(1682087458.735:222): prog-id=55 op=UNLOAD
Apr 21 14:30:58 homeassistant kernel: audit: type=1334 audit(1682087458.735:223): prog-id=54 op=UNLOAD
Apr 21 14:30:58 homeassistant kernel: audit: type=1334 audit(1682087458.735:224): prog-id=53 op=UNLOAD
Apr 21 14:30:59 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Apr 21 14:30:59 homeassistant kernel: audit: type=1334 audit(1682087459.086:225): prog-id=58 op=UNLOAD
Apr 21 14:30:59 homeassistant kernel: audit: type=1334 audit(1682087459.086:226): prog-id=57 op=UNLOAD
Apr 21 14:30:59 homeassistant kernel: audit: type=1334 audit(1682087459.086:227): prog-id=56 op=UNLOAD
Apr 21 14:38:06 homeassistant systemd-resolved[425]: Grace period over, resuming full feature set (UDP+EDNS0) for DNS server 192.168.1.1.
Apr 21 14:39:35 homeassistant systemd-resolved[425]: Grace period over, resuming full feature set (UDP+EDNS0) for DNS server 192.168.1.1.
Apr 21 14:44:03 homeassistant systemd[1]: Starting Cleanup of Temporary Directories...
Apr 21 14:44:03 homeassistant systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
Apr 21 14:44:03 homeassistant systemd[1]: Finished Cleanup of Temporary Directories.
Apr 21 14:44:03 homeassistant systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dclean.service.mount: Deactivated successfully.
Apr 21 14:53:37 homeassistant dockerd[537]: time="2023-04-21T14:53:37.881991386Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;checkonline.home-assistant.io.\tIN\t A" error="read udp 172.30.232.2:50638->192.168.1.1:53: i/o timeout"
Apr 21 14:53:37 homeassistant dockerd[537]: time="2023-04-21T14:53:37.941306831Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;github.com.\tIN\t A" error="read udp 172.30.232.2:51384->192.168.1.1:53: i/o timeout"
Apr 21 14:53:40 homeassistant dockerd[537]: time="2023-04-21T14:53:40.444018392Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;github.com.\tIN\t AAAA" error="read udp 172.30.232.2:35692->192.168.1.1:53: i/o timeout"
Apr 21 14:54:48 homeassistant dockerd[537]: time="2023-04-21T14:54:48.919853889Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;github.com.\tIN\t A" error="read udp 172.30.232.2:55065->192.168.1.1:53: i/o timeout"
Apr 21 14:55:28 homeassistant dockerd[537]: time="2023-04-21T14:55:28.787591149Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;github.com.\tIN\t A" error="read udp 172.30.232.2:36888->192.168.1.1:53: i/o timeout"
Apr 21 14:55:28 homeassistant dockerd[537]: time="2023-04-21T14:55:28.811536453Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;github.com.\tIN\t A" error="read udp 172.30.232.2:40904->192.168.1.1:53: i/o timeout"
Apr 21 14:56:13 homeassistant dockerd[537]: time="2023-04-21T14:56:13.480448576Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;version.home-assistant.io.\tIN\t A" error="read udp 172.30.232.2:37302->192.168.1.1:53: i/o timeout"
Apr 21 14:56:35 homeassistant systemd[1]: docker-d8a4bc88cb6a15069d584f4ae8e58e993a6d4afbfd1bde94497bab7ea3d4193d.scope: Deactivated successfully.
Apr 21 14:56:35 homeassistant systemd[1]: docker-d8a4bc88cb6a15069d584f4ae8e58e993a6d4afbfd1bde94497bab7ea3d4193d.scope: Consumed 1min 27.970s CPU time.
Apr 21 14:56:35 homeassistant dockerd[537]: time="2023-04-21T14:56:35.646789762Z" level=info msg="ignoring event" container=d8a4bc88cb6a15069d584f4ae8e58e993a6d4afbfd1bde94497bab7ea3d4193d module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Apr 21 14:56:35 homeassistant kernel: audit: type=1334 audit(1682088995.648:228): prog-id=44 op=UNLOAD
Apr 21 14:56:35 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-d8a4bc88cb6a15069d584f4ae8e58e993a6d4afbfd1bde94497bab7ea3d4193d-runc.Oc7ii6.mount: Deactivated successfully.
Apr 21 14:56:35 homeassistant systemd[1]: Started libcontainer container d8a4bc88cb6a15069d584f4ae8e58e993a6d4afbfd1bde94497bab7ea3d4193d.
Apr 21 14:56:36 homeassistant kernel: audit: type=1334 audit(1682088996.008:229): prog-id=59 op=LOAD
Apr 21 14:56:36 homeassistant kernel: audit: type=1300 audit(1682088996.008:229): arch=c00000b7 syscall=280 success=yes exit=14 a0=5 a1=4000137700 a2=78 a3=0 items=0 ppid=4991 pid=5001 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Apr 21 14:56:36 homeassistant kernel: audit: type=1327 audit(1682088996.008:229): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F64386134626338386362366131353036396435383466346165
Apr 21 14:56:36 homeassistant kernel: audit: type=1334 audit(1682088996.008:230): prog-id=60 op=LOAD
Apr 21 14:56:36 homeassistant kernel: audit: type=1300 audit(1682088996.008:230): arch=c00000b7 syscall=280 success=yes exit=16 a0=5 a1=4000137490 a2=78 a3=0 items=0 ppid=4991 pid=5001 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Apr 21 14:56:36 homeassistant kernel: audit: type=1327 audit(1682088996.008:230): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F64386134626338386362366131353036396435383466346165
Apr 21 14:56:36 homeassistant kernel: audit: type=1334 audit(1682088996.008:231): prog-id=60 op=UNLOAD
Apr 21 14:56:36 homeassistant kernel: audit: type=1334 audit(1682088996.008:232): prog-id=59 op=UNLOAD
Apr 21 14:56:36 homeassistant kernel: audit: type=1334 audit(1682088996.008:233): prog-id=61 op=LOAD
Apr 21 14:56:47 homeassistant dockerd[537]: time="2023-04-21T14:56:47.421353768Z" level=warning msg="[resolver] failed to read from DNS server: 192.168.1.1:53, query: ;github.com.\tIN\t A" error="read udp 172.30.232.2:49691->192.168.1.1:53: i/o timeout"
Apr 21 15:14:06 homeassistant kernel: kauditd_printk_skb: 2 callbacks suppressed
Apr 21 15:14:06 homeassistant kernel: audit: type=1334 audit(1682090046.574:234): prog-id=62 op=LOAD
Apr 21 15:14:06 homeassistant systemd-timesyncd[527]: Network configuration changed, trying to establish connection.
Apr 21 15:14:06 homeassistant systemd[1]: Started Journal Gateway Service.
Apr 21 15:14:06 homeassistant systemd-timesyncd[527]: Contacted time server 162.159.200.1:123 (time.cloudflare.com).
Apr 21 15:14:06 homeassistant systemd-journal-gatewayd[5806]: microhttpd: MHD_OPTION_EXTERNAL_LOGGER is not the first option specified for the daemon. Some messages may be printed by the standard MHD logger.
```

### Additional information

Missing official add-ons and esphome

**Comment by SlimPugGamer** [comment]
Fixed by rebooting
