### ISSUE TITLE
HA Unable to Install Utilizing Nighthawk Router

### ISSUE THREAD

**Issue by jschluet13** [home-assistant/operating-system#2564]
### Describe the issue you are experiencing

Very long and painful first install took place with a lot of greatly appreciated support from the discord channel.  

The problem appeared to be a DNS issue.  After going into my R6900v2 settings and making the DNS 9.9.9.9 and 1.1.1.1, then setting that in ha, it still was not connecting.  Log below, it shows the unable to connect to the ghcr.io even though my desktop and phone (both on wifi) could get there fine.  I could also ping out and curl.

Eventually, we found some old threads about Nighthawk routers causing some issues, and went down that rabbit hole.  I tethered my WYSE 5070 to my desktop and then ran the desktop off my phone mobile hotspot and the install worked perfect.  That being said, I still won't be able to connect for updates so I would like some assistance trying to find a permanent functional solution.  

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.Download latest image from github link on: https://www.home-assistant.io/installation/generic-x86-64 and place on usb#1
2.Download Balena Etcher and also place on usb#1
3.Download and create bootable live instance of Ubuntu on usb#2
4.Boot to ubs#2 live version
5.Install Balena Etcher from usb#1
6.Flash image from usb#1 onto main drive of WYSE 5070
7.Shutdown live Ubuntu and remove both usb
8.Boot up the WYSE into the new HA
9.Set DNS to 9.9.9.9 and 1.1.1.1, also disable IPv6 per discord recommendation
10.Watch it fail
...

### Anything in the Supervisor logs that might be useful for us?

```txt
23-05-25 02:40:29 INFO (SyncWorker_0) [supervisor.docker.homeassistant] Starting Home Assistant ghcr.io/home-assistant/generic-x86-64-homeassistant with version landingpage
23-05-25 02:40:29 INFO (MainThread) [supervisor.os.manager] Detect Home Assistant Operating System 10.1 / BootSlot A
23-05-25 02:40:29 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
23-05-25 02:40:29 INFO (SyncWorker_1) [supervisor.docker.interface] Starting homeassistant
23-05-25 02:40:29 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
23-05-25 02:40:29 INFO (SyncWorker_1) [supervisor.docker.interface] Starting homeassistant
23-05-25 02:40:30 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
23-05-25 02:40:30 INFO (SyncWorker_1) [supervisor.docker.interface] Starting homeassistant
23-05-25 02:40:30 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
23-05-25 02:40:30 INFO (SyncWorker_1) [supervisor.docker.interface] Starting homeassistant
23-05-25 02:40:30 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
23-05-25 02:40:30 INFO (SyncWorker_1) [supervisor.docker.interface] Starting homeassistant
23-05-25 02:40:30 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
23-05-25 02:40:30 INFO (SyncWorker_1) [supervisor.docker.interface] Starting homeassistant
23-05-25 02:40:31 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
23-05-25 02:40:31 INFO (SyncWorker_1) [supervisor.docker.interface] Starting homeassistant
23-05-25 02:40:31 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
23-05-25 02:40:31 INFO (SyncWorker_1) [supervisor.docker.interface] Starting homeassistant
23-05-25 02:40:31 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
23-05-25 02:40:31 INFO (SyncWorker_1) [supervisor.docker.interface] Starting homeassistant
23-05-25 02:40:31 WARNING (MainThread) [supervisor.homeassistant.core] Watchdog found Home Assistant failed, restarting...
23-05-25 02:40:31 INFO (SyncWorker_1) [supervisor.docker.interface] Starting homeassistant
23-05-25 02:40:32 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1727' coro=<HomeAssistantCore.watchdog_container() done, defined at /usr/src/supervisor/supervisor/homeassistant/core.py:453> exception=JobException('Rate limit exceeded, more then 10 calls in 0:30:00')>
Traceback (most recent call last):
File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 459, in watchdog_container
await self._restart_after_problem(event.state)
File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 144, in wrapper
raise on_condition(
supervisor.exceptions.JobException: Rate limit exceeded, more then 10 calls in 0:30:00
23-05-25 02:40:34 WARNING (MainThread) [supervisor.jobs] 'GitRepo.clone' blocked from execution, no supervisor internet connection

23-05-26 15:46:24 INFO (SyncWorker_1) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/generic-x86-64-homeassistant:landingpage to ghcr.io/home-assistant/generic-x86-64-homeassistant:2023.5.4
23-05-26 15:46:24 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/generic-x86-64-homeassistant with tag 2023.5.4.
23-05-26 15:48:30 INFO (MainThread) [supervisor.host.network] Updating local network information
23-05-26 15:52:49 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/generic-x86-64-homeassistant:2023.5.4: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2023.5.4&fromImage=ghcr.io%2Fhome-assistant%2Fgeneric-x86-64-homeassistant&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)")
23-05-26 15:52:49 WARNING (MainThread) [supervisor.homeassistant.core] Error on Home Assistant installation. Retry in 30sec
23-05-26 15:53:19 INFO (SyncWorker_2) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/generic-x86-64-homeassistant:landingpage to ghcr.io/home-assistant/generic-x86-64-homeassistant:2023.5.4
23-05-26 15:53:19 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/generic-x86-64-homeassistant with tag 2023.5.4.
23-05-26 15:58:57 ERROR (SyncWorker_2) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/generic-x86-64-homeassistant:2023.5.4: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2023.5.4&fromImage=ghcr.io%2Fhome-assistant%2Fgeneric-x86-64-homeassistant&platform=linux%2Famd64: Internal Server Error ("Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)")
23-05-26 15:58:57 WARNING (MainThread) [supervisor.homeassistant.core] Error on Home Assistant installation. Retry in 30sec
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

**Comment by agners** [comment]
I've tried to reproduce this issue previously, unfortunately, I really wasn't able to reproduce (see details in https://github.com/home-assistant/operating-system/issues/2182#issuecomment-1429479258).

It seems to be a combination of Router & ISP which causes the issue. My best guess is that your ISP is blocking DNS and/or NTP service of third party providers (Google/Cloudflare).

Some routers provide their own NTP service. Unfortunately, the manual of this router has no information about NTP at all :cry: I found [this steps at a random website](https://www.hardreset.info/devices/netgear/netgear-r6900v2/faq/date-time/router-date-time/) which supposedly should set an NTP server, has your router such an "NTP Server" setting at that place? If so, can you try to enter an NTP server as provided by your ISP?
