### ISSUE TITLE
Backups not shown on Network Drive

### ISSUE THREAD

**Issue by requiemmg** [home-assistant/operating-system#2646]
### Describe the issue you are experiencing

Backups are not shown on the Supervisor Frontend (Config->system->backups) when choosing a network drive.

![grafik](https://github.com/home-assistant/operating-system/assets/11157808/51da2766-3af0-4d1c-83b9-e78f13cc7b68)

Please also see this thread on the forums: https://community.home-assistant.io/t/backups-not-shown/592136

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

core-2023.7.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Choose a Samba Share as the default backup location
2. Perform backups
3. Backups are physically being created but are not shown on the GUI which says "You don't have any backups yet"
4. To restore a backup, you then need to use the "Upload Backup" functionality

### Anything in the Supervisor logs that might be useful for us?

```txt
23-07-20 08:18:51 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_nodered
23-07-20 08:18:51 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 5c53de3b_esphome
23-07-20 08:18:51 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 5c53de3b_esphome
23-07-20 08:18:51 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_letsencrypt
23-07-20 08:18:51 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_letsencrypt
23-07-20 08:18:51 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on db21ed7f_teamspeak
23-07-20 08:20:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon db21ed7f_teamspeak
23-07-20 08:20:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_silabs_multiprotocol
23-07-20 08:20:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_silabs_multiprotocol
23-07-20 08:20:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_samba
23-07-20 08:20:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_samba
23-07-20 08:20:28 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on cebe7a76_hassio_google_drive_backup
23-07-20 08:20:28 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon cebe7a76_hassio_google_drive_backup
23-07-20 08:20:29 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
23-07-20 08:24:53 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
23-07-20 08:24:53 INFO (MainThread) [supervisor.backups.manager] Backing up 38ac5a0a store folders
23-07-20 08:24:53 INFO (SyncWorker_1) [supervisor.backups.backup] Backing up folder share
23-07-20 08:24:53 INFO (SyncWorker_1) [supervisor.backups.backup] Backup folder share done
23-07-20 08:24:53 INFO (SyncWorker_0) [supervisor.backups.backup] Backing up folder addons/local
23-07-20 08:24:53 INFO (SyncWorker_0) [supervisor.backups.backup] Backup folder addons/local done
23-07-20 08:24:53 INFO (SyncWorker_5) [supervisor.backups.backup] Backing up folder ssl
23-07-20 08:24:53 INFO (SyncWorker_5) [supervisor.backups.backup] Backup folder ssl done
23-07-20 08:24:53 INFO (SyncWorker_4) [supervisor.backups.backup] Backing up folder media
23-07-20 08:24:53 INFO (SyncWorker_4) [supervisor.backups.backup] Backup folder media done
23-07-20 08:26:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-07-20 08:26:41 INFO (MainThread) [supervisor.backups.manager] Creating full backup with slug 38ac5a0a completed
23-07-20 08:26:42 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-07-20 08:26:42 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-07-20 08:26:42 INFO (MainThread) [supervisor.api.middleware.security] /backups/38ac5a0a/info access from cebe7a76_hassio_google_drive_backup
23-07-20 08:26:43 INFO (MainThread) [supervisor.api.middleware.security] /backups/8d89b45e access from cebe7a76_hassio_google_drive_backup
23-07-20 08:26:43 INFO (MainThread) [supervisor.backups.manager] Removed backup file 8d89b45e
23-07-20 08:26:43 INFO (MainThread) [supervisor.api.middleware.security] /backups/38ac5a0a/download access from cebe7a76_hassio_google_drive_backup
23-07-20 08:26:43 INFO (MainThread) [supervisor.api.backups] Downloading backup 38ac5a0a
23-07-20 08:29:46 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-130893' coro=<WSClient.start_listener() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:88> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in start_listener
    await self._receive_json()
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 104, in _receive_json
    msg = await self._client.receive()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_ws.py", line 265, in receive
    await self.pong(msg.data)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_ws.py", line 146, in pong
    await self._writer.pong(message)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 670, in pong
    await self._send_frame(message, WSMsgType.PONG)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
23-07-20 08:29:46 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-137105' coro=<WebSocketWriter.ping() done, defined at /usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py:672> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
23-07-20 08:29:46 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-137106' coro=<WebSocketWriter.ping() done, defined at /usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py:672> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
23-07-20 08:29:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot write to closing transport
23-07-20 08:29:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Cannot write to closing transport
23-07-20 08:29:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-07-20 08:29:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-07-20 08:29:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-07-20 08:29:47 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-07-20 08:29:47 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-07-20 08:29:52 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-07-20 08:29:52 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-07-20 08:29:52 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-07-20 08:30:11 INFO (MainThread) [supervisor.backups.manager] Found 14 backup files
23-07-20 08:30:18 INFO (MainThread) [supervisor.backups.manager] Found 14 backup files
23-07-20 08:32:11 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-136966' coro=<RequestHandler.start() done, defined at /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:462> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 505, in start
    request = self._request_factory(message, payload, self, writer, handler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 446, in _make_request
    return _cls(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_request.py", line 811, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_request.py", line 188, in __init__
    assert transport is not None
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Anything in the Host logs that might be useful for us?

```txt
Jul 20 06:18:50 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.E7B0vt.mount: Deactivated successfully.
Jul 20 06:18:52 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-c94f29cf1569a546584fd36a5a21532ec29cc7218c2c8b7b140f869f4e31e545-runc.qMcRqg.mount: Deactivated successfully.
Jul 20 06:19:22 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-c94f29cf1569a546584fd36a5a21532ec29cc7218c2c8b7b140f869f4e31e545-runc.JSukyE.mount: Deactivated successfully.
Jul 20 06:19:22 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-6aece4a77b9075a06b5c8927d3c76cd1e2a25bd85440d02546a76dc0367747a8-runc.pPDo3R.mount: Deactivated successfully.
Jul 20 06:19:51 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.214aYC.mount: Deactivated successfully.
Jul 20 06:19:52 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-c94f29cf1569a546584fd36a5a21532ec29cc7218c2c8b7b140f869f4e31e545-runc.TAWbZt.mount: Deactivated successfully.
Jul 20 06:20:23 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-6aece4a77b9075a06b5c8927d3c76cd1e2a25bd85440d02546a76dc0367747a8-runc.BGJV6B.mount: Deactivated successfully.
Jul 20 06:20:32 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.pQ179L.mount: Deactivated successfully.
Jul 20 06:20:42 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.J5vQbF.mount: Deactivated successfully.
Jul 20 06:20:52 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.FSunMG.mount: Deactivated successfully.
Jul 20 06:21:44 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.2etdt9.mount: Deactivated successfully.
Jul 20 06:22:24 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-6aece4a77b9075a06b5c8927d3c76cd1e2a25bd85440d02546a76dc0367747a8-runc.nBA5pt.mount: Deactivated successfully.
Jul 20 06:22:55 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.M8BVtL.mount: Deactivated successfully.
Jul 20 06:23:55 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-c94f29cf1569a546584fd36a5a21532ec29cc7218c2c8b7b140f869f4e31e545-runc.p7OiGQ.mount: Deactivated successfully.
Jul 20 06:24:25 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-6aece4a77b9075a06b5c8927d3c76cd1e2a25bd85440d02546a76dc0367747a8-runc.gN9PX5.mount: Deactivated successfully.
Jul 20 06:24:28 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.oYEOIw.mount: Deactivated successfully.
Jul 20 06:24:53 homeassistant kernel: cifs_open_info_to_fattr: 4 callbacks suppressed
Jul 20 06:24:53 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:24:55 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-6aece4a77b9075a06b5c8927d3c76cd1e2a25bd85440d02546a76dc0367747a8-runc.FqGuF4.mount: Deactivated successfully.
Jul 20 06:24:59 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.az6wSq.mount: Deactivated successfully.
Jul 20 06:26:10 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.OcufUF.mount: Deactivated successfully.
Jul 20 06:26:20 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.CrFFPF.mount: Deactivated successfully.
Jul 20 06:26:42 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:26:42 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:26:42 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:26:42 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:26:42 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:26:42 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:26:42 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:26:42 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:26:42 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:26:42 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:26:56 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-c94f29cf1569a546584fd36a5a21532ec29cc7218c2c8b7b140f869f4e31e545-runc.3TEoTI.mount: Deactivated successfully.
Jul 20 06:27:32 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.juIwaN.mount: Deactivated successfully.
Jul 20 06:27:56 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-c94f29cf1569a546584fd36a5a21532ec29cc7218c2c8b7b140f869f4e31e545-runc.hgvgK7.mount: Deactivated successfully.
Jul 20 06:28:02 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.3owNci.mount: Deactivated successfully.
Jul 20 06:28:27 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-6aece4a77b9075a06b5c8927d3c76cd1e2a25bd85440d02546a76dc0367747a8-runc.UicAUr.mount: Deactivated successfully.
Jul 20 06:28:53 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.L2qrl3.mount: Deactivated successfully.
Jul 20 06:28:57 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-c94f29cf1569a546584fd36a5a21532ec29cc7218c2c8b7b140f869f4e31e545-runc.cmrIiy.mount: Deactivated successfully.
Jul 20 06:28:57 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-6aece4a77b9075a06b5c8927d3c76cd1e2a25bd85440d02546a76dc0367747a8-runc.jLlL1Y.mount: Deactivated successfully.
Jul 20 06:29:13 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.wqndKj.mount: Deactivated successfully.
Jul 20 06:29:44 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.dKlav7.mount: Deactivated successfully.
Jul 20 06:29:46 homeassistant kernel: cifs_open_info_to_fattr: 5 callbacks suppressed
Jul 20 06:29:46 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:29:46 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:29:46 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:29:46 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:29:46 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:29:46 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:29:46 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:29:46 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:29:46 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:29:46 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:29:57 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-6aece4a77b9075a06b5c8927d3c76cd1e2a25bd85440d02546a76dc0367747a8-runc.GNdcHn.mount: Deactivated successfully.
Jul 20 06:30:10 homeassistant kernel: cifs_open_info_to_fattr: 3 callbacks suppressed
Jul 20 06:30:10 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:10 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:10 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:10 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:10 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:10 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:10 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:10 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:10 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:10 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:20 homeassistant kernel: cifs_open_info_to_fattr: 5 callbacks suppressed
Jul 20 06:30:20 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:21 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:26 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:26 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:26 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:26 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:26 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:26 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:26 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:26 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:26 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:26 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:30:35 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.RMTIjq.mount: Deactivated successfully.
Jul 20 06:30:55 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.iX2ObA.mount: Deactivated successfully.
Jul 20 06:31:27 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-c94f29cf1569a546584fd36a5a21532ec29cc7218c2c8b7b140f869f4e31e545-runc.d24rTH.mount: Deactivated successfully.
Jul 20 06:31:46 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.o0y5bs.mount: Deactivated successfully.
Jul 20 06:32:29 homeassistant kernel: cifs_open_info_to_fattr: 1 callbacks suppressed
Jul 20 06:32:29 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:32:29 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:32:29 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:32:29 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:32:29 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:32:29 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:32:29 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:32:29 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:32:29 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:32:29 homeassistant kernel: CIFS: VFS: bogus file nlink value 0
Jul 20 06:32:47 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8055a7cd234dae69488f40b2a2c9daf12fea7543c59c9360d1f4fdcb138b13e8-runc.qFBhUx.mount: Deactivated successfully.
Jul 20 06:32:58 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-c94f29cf1569a546584fd36a5a21532ec29cc7218c2c8b7b140f869f4e31e545-runc.EXornD.mount: Deactivated successfully.
Jul 20 06:33:16 homeassistant kernel: kauditd_printk_skb: 38 callbacks suppressed
Jul 20 06:33:16 homeassistant kernel: audit: type=1334 audit(1689834796.312:480): prog-id=138 op=LOAD
Jul 20 06:33:16 homeassistant systemd-timesyncd[1264]: Network configuration changed, trying to establish connection.
Jul 20 06:33:16 homeassistant systemd-timesyncd[1264]: Contacted time server 192.168.0.1:123 (192.168.0.1).
Jul 20 06:33:16 homeassistant systemd[1]: Started Journal Gateway Service.
Jul 20 06:33:16 homeassistant systemd-journal-gatewayd[125786]: microhttpd: MHD_OPTION_EXTERNAL_LOGGER is not the first option specified for the daemon. Some messages may be printed by the standard MHD logger.
```

## System Information

version | core-2023.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4862
Installed Version | 1.32.1
Stage | running
Available Repositories | 1273
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.5 GB
disk_used | 16.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Studio Code Server (5.8.2), Tautulli (3.2.8), Filebrowser (2.23.0-5), Epic Games Free (bullseye-slim-2023-07-10), Mosquitto broker (6.2.1), modbus-proxy (1.0.15), Node-RED (14.4.0), ESPHome (2023.7.0), Let's Encrypt (4.12.9), Teamspeak server (3.13.6-8), Silicon Labs Multiprotocol (2.3.0), Samba share (10.0.2), Home Assistant Google Drive Backup (0.111.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 7
views | 5
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 0.1.14
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 18. Juli 2023 um 13:21
-- | --
current_recorder_run | 20. Juli 2023 um 07:47
estimated_db_size | 2647.94 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by agners** [comment]
> kernel: CIFS: VFS: bogus file nlink value 0

It seems something is wrong with that SMB server/share. Maybe the server manages the files on that share, which confuses the client (there is  technical descirption here: https://unix.stackexchange.com/questions/185161/what-are-bogus-file-nlink-values).

Does restarting the system brings them back?

**Comment by requiemmg** [comment]
The current samba share is just a usb drive connected to my Router (AVM Fritz Box 6591 Cable) which offers a samba share. Behaviour doesn't change after either reboot of the router or the HA system. Behaviour was the same when the network share was located on a windows server system.
Sometimes the backups will start to show up after leaving the window open a while, most times not.

**Comment by agners** [comment]
> Sometimes the backups will start to show up after leaving the window open a while, most times not.

Ah yes, loading them does take a while. But that is a Supervisor issue, it is not really related to the OS.

**Comment by requiemmg** [comment]
Taking a while is ok.
But as I said:
1. Most times it wont load at all
2. If it takes a while to load,it should say "loading", not "you have no backups" 😉
