### ISSUE TITLE
There is something wrong with asyncio.Protocol in OS systems

### ISSUE THREAD

**Issue by NJPYY** [home-assistant/operating-system#3028]
### Describe the issue you are experiencing

When I used `class TuyaProtocol(asyncio.Protocol, ContextualLogger)` to control the device in a locally deployed development environment, everything worked fine
But
When I control the device in **HAOS**, it doesn't work.
The log shows that `transport.write` is normal, but the device is not responding, I am pretty sure it is not a problem with the device,I suspect the data was not sent successfully.
This only happens in **OS**

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

10.5

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1.Implement a custom protocol using `asyncio.Protocol`
2.Connect to gateway devices or other devices that can be connected(I'm using tuya's zigbee gateway)
3.Send multiple control instructions using `transport.write`

### Anything in the Supervisor logs that might be useful for us?

```txt
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.addons.manager] Phase 'application' starting 0 add-ons[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.core] Supervisor is up and running[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.resolution.fixups.store_execute_reset] Reset corrupt Store: core[0m
[32m24-01-02 09:44:49 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/home-assistant/addons repository[0m
[32m24-01-02 09:46:39 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[31m24-01-02 09:47:11 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/esphome/home-assistant-addon repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/esphome/home-assistant-addon/': SSL connection timeout'.[0m
[32m24-01-02 09:47:11 INFO (MainThread) [supervisor.resolution.module] Create new suggestion execute_reset - store / 5c53de3b[0m
[32m24-01-02 09:47:11 INFO (MainThread) [supervisor.resolution.module] Create new issue corrupt_repository - store / 5c53de3b[0m
[32m24-01-02 09:47:11 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove[0m
[32m24-01-02 09:47:11 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove[0m
[31m24-01-02 09:47:11 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-422' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 600, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/home-assistant/addons/': Failure when receiving data from the peer'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 296, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 289, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError[0m
[31m24-01-02 09:47:11 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-421' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 600, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/esphome/home-assistant-addon/': SSL connection timeout'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 296, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 289, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError[0m
[32m24-01-02 10:12:49 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
```

### Anything in the Host logs that might be useful for us?

```txt
Jan 02 01:41:15 homeassistant-brains systemd[1]: var-lib-docker-overlay2-14d4e3a73e3b8f66ede1153d7de595f51d3e4baa3b1545f434966cf90a0b2c90\x2dinit-merged.mount: Deactivated successfully.
Jan 02 01:41:15 homeassistant-brains systemd[1]: mnt-data-docker-overlay2-14d4e3a73e3b8f66ede1153d7de595f51d3e4baa3b1545f434966cf90a0b2c90\x2dinit-merged.mount: Deactivated successfully.
Jan 02 01:41:15 homeassistant-brains systemd[1]: Started libcontainer container 36023644fbbc899764f38e977ef14396a6417332f109cf89a2d9a9d801ac78c1.
Jan 02 01:41:16 homeassistant-brains systemd[1]: Starting Bluetooth service...
Jan 02 01:41:16 homeassistant-brains bluetoothd[1929]: Bluetooth daemon 5.66
Jan 02 01:41:16 homeassistant-brains systemd[1]: Started Bluetooth service.
Jan 02 01:41:16 homeassistant-brains bluetoothd[1929]: Starting SDP server
Jan 02 01:41:16 homeassistant-brains kernel: Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Jan 02 01:41:16 homeassistant-brains kernel: Bluetooth: BNEP filters: protocol multicast
Jan 02 01:41:16 homeassistant-brains kernel: Bluetooth: BNEP socket layer initialized
Jan 02 01:41:16 homeassistant-brains bluetoothd[1929]: Bluetooth management interface 1.22 initialized
Jan 02 01:41:23 homeassistant-brains systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
Jan 02 01:41:43 homeassistant-brains systemd[1]: systemd-timedated.service: Deactivated successfully.
Jan 02 01:41:43 homeassistant-brains kernel: kauditd_printk_skb: 127 callbacks suppressed
Jan 02 01:41:43 homeassistant-brains kernel: audit: type=1334 audit(1704159703.283:169): prog-id=25 op=UNLOAD
Jan 02 01:41:43 homeassistant-brains kernel: audit: type=1334 audit(1704159703.283:170): prog-id=24 op=UNLOAD
Jan 02 01:41:43 homeassistant-brains kernel: audit: type=1334 audit(1704159703.283:171): prog-id=23 op=UNLOAD
Jan 02 01:41:46 homeassistant-brains systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jan 02 01:41:46 homeassistant-brains kernel: audit: type=1334 audit(1704159706.382:172): prog-id=14 op=UNLOAD
Jan 02 01:41:46 homeassistant-brains kernel: audit: type=1334 audit(1704159706.382:173): prog-id=13 op=UNLOAD
Jan 02 01:41:46 homeassistant-brains kernel: audit: type=1334 audit(1704159706.382:174): prog-id=12 op=UNLOAD
Jan 02 01:42:02 homeassistant-brains systemd[1]: var-lib-docker-overlay2-d1a2d30d03f4dddeeca21db86f9cd36fbf935543278b571148562ece21c3758c\x2dinit-merged.mount: Deactivated successfully.
Jan 02 01:42:02 homeassistant-brains systemd[1]: mnt-data-docker-overlay2-d1a2d30d03f4dddeeca21db86f9cd36fbf935543278b571148562ece21c3758c\x2dinit-merged.mount: Deactivated successfully.
Jan 02 01:42:03 homeassistant-brains systemd[1]: Started libcontainer container d9e2a0b644e620e0c7d3c6ef8b5e20ea74aa34dfcf63ce481fb086690fcb7937.
Jan 02 01:42:03 homeassistant-brains kernel: audit: type=1334 audit(1704159723.057:175): prog-id=42 op=LOAD
Jan 02 01:42:03 homeassistant-brains kernel: audit: type=1334 audit(1704159723.058:176): prog-id=43 op=LOAD
Jan 02 01:42:03 homeassistant-brains kernel: audit: type=1300 audit(1704159723.058:176): arch=c000003e syscall=321 success=yes exit=15 a0=5 a1=c00018d7f8 a2=78 a3=0 items=0 ppid=2028 pid=2039 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Jan 02 01:42:03 homeassistant-brains kernel: audit: type=1327 audit(1704159723.058:176): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F64396532613062363434653632306530633764336336656638
Jan 02 01:42:03 homeassistant-brains kernel: audit: type=1334 audit(1704159723.058:177): prog-id=44 op=LOAD
Jan 02 01:42:03 homeassistant-brains kernel: audit: type=1300 audit(1704159723.058:177): arch=c000003e syscall=321 success=yes exit=17 a0=5 a1=c00018d590 a2=78 a3=0 items=0 ppid=2028 pid=2039 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Jan 02 01:42:03 homeassistant-brains kernel: audit: type=1327 audit(1704159723.058:177): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F64396532613062363434653632306530633764336336656638
Jan 02 01:42:03 homeassistant-brains kernel: audit: type=1334 audit(1704159723.058:178): prog-id=44 op=UNLOAD
Jan 02 01:42:03 homeassistant-brains kernel: audit: type=1334 audit(1704159723.058:179): prog-id=43 op=UNLOAD
Jan 02 01:42:03 homeassistant-brains kernel: audit: type=1334 audit(1704159723.058:180): prog-id=45 op=LOAD
Jan 02 01:42:03 homeassistant-brains kernel: hassio: port 6(veth3b42e83) entered blocking state
Jan 02 01:42:03 homeassistant-brains kernel: hassio: port 6(veth3b42e83) entered disabled state
Jan 02 01:42:03 homeassistant-brains kernel: device veth3b42e83 entered promiscuous mode
Jan 02 01:42:03 homeassistant-brains NetworkManager[396]: <info>  [1704159723.2577] manager: (vethac6fcaa): new Veth device (/org/freedesktop/NetworkManager/Devices/17)
Jan 02 01:42:03 homeassistant-brains NetworkManager[396]: <info>  [1704159723.2600] manager: (veth3b42e83): new Veth device (/org/freedesktop/NetworkManager/Devices/18)
Jan 02 01:42:03 homeassistant-brains systemd[1]: Started libcontainer container 86acc816e5779ecfb06fe0317f5504756ebcf6617f965cd8d18c5a4f5273a87c.
Jan 02 01:42:03 homeassistant-brains kernel: eth0: renamed from vethac6fcaa
Jan 02 01:42:03 homeassistant-brains kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth3b42e83: link becomes ready
Jan 02 01:42:03 homeassistant-brains kernel: hassio: port 6(veth3b42e83) entered blocking state
Jan 02 01:42:03 homeassistant-brains kernel: hassio: port 6(veth3b42e83) entered forwarding state
Jan 02 01:42:03 homeassistant-brains NetworkManager[396]: <info>  [1704159723.4807] device (veth3b42e83): carrier: link connected
Jan 02 01:42:08 homeassistant-brains systemd[1]: Started libcontainer container 3d20b21c9e740e9e70bbf0f2b984d76ce618d43b9e742ca033cd65ead26aaad2.
Jan 02 01:42:08 homeassistant-brains kernel: kauditd_printk_skb: 41 callbacks suppressed
Jan 02 01:42:08 homeassistant-brains kernel: audit: type=1334 audit(1704159728.728:196): prog-id=50 op=LOAD
Jan 02 01:42:08 homeassistant-brains kernel: audit: type=1300 audit(1704159728.728:196): arch=c000003e syscall=321 success=yes exit=14 a0=5 a1=c0001ad7f8 a2=78 a3=0 items=0 ppid=2487 pid=2498 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Jan 02 01:42:08 homeassistant-brains kernel: audit: type=1327 audit(1704159728.728:196): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F33643230623231633965373430653965373062626630663262
Jan 02 01:42:08 homeassistant-brains kernel: audit: type=1334 audit(1704159728.728:197): prog-id=51 op=LOAD
Jan 02 01:42:08 homeassistant-brains kernel: audit: type=1300 audit(1704159728.728:197): arch=c000003e syscall=321 success=yes exit=16 a0=5 a1=c0001ad590 a2=78 a3=0 items=0 ppid=2487 pid=2498 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Jan 02 01:42:08 homeassistant-brains kernel: audit: type=1327 audit(1704159728.728:197): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F33643230623231633965373430653965373062626630663262
Jan 02 01:42:08 homeassistant-brains kernel: audit: type=1334 audit(1704159728.728:198): prog-id=51 op=UNLOAD
Jan 02 01:42:08 homeassistant-brains kernel: audit: type=1334 audit(1704159728.728:199): prog-id=50 op=UNLOAD
Jan 02 01:42:08 homeassistant-brains kernel: audit: type=1334 audit(1704159728.728:200): prog-id=52 op=LOAD
Jan 02 01:42:08 homeassistant-brains kernel: audit: type=1300 audit(1704159728.728:200): arch=c000003e syscall=321 success=yes exit=14 a0=5 a1=c0001ada50 a2=78 a3=0 items=0 ppid=2487 pid=2498 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Jan 02 01:44:49 homeassistant-brains kernel: kauditd_printk_skb: 1 callbacks suppressed
Jan 02 01:44:49 homeassistant-brains kernel: audit: type=1334 audit(1704159889.121:201): prog-id=53 op=LOAD
Jan 02 01:44:49 homeassistant-brains kernel: audit: type=1334 audit(1704159889.121:202): prog-id=54 op=LOAD
Jan 02 01:44:49 homeassistant-brains kernel: audit: type=1334 audit(1704159889.121:203): prog-id=55 op=LOAD
Jan 02 01:44:49 homeassistant-brains systemd[1]: Starting Hostname Service...
Jan 02 01:44:49 homeassistant-brains systemd[1]: Started Hostname Service.
Jan 02 01:44:49 homeassistant-brains kernel: audit: type=1334 audit(1704159889.252:204): prog-id=56 op=LOAD
Jan 02 01:44:49 homeassistant-brains kernel: audit: type=1334 audit(1704159889.252:205): prog-id=57 op=LOAD
Jan 02 01:44:49 homeassistant-brains kernel: audit: type=1334 audit(1704159889.253:206): prog-id=58 op=LOAD
Jan 02 01:44:49 homeassistant-brains systemd[1]: Starting Time & Date Service...
Jan 02 01:44:49 homeassistant-brains systemd[1]: Started Time & Date Service.
Jan 02 01:45:19 homeassistant-brains systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jan 02 01:45:19 homeassistant-brains kernel: audit: type=1334 audit(1704159919.311:207): prog-id=55 op=UNLOAD
Jan 02 01:45:19 homeassistant-brains kernel: audit: type=1334 audit(1704159919.311:208): prog-id=54 op=UNLOAD
Jan 02 01:45:19 homeassistant-brains kernel: audit: type=1334 audit(1704159919.311:209): prog-id=53 op=UNLOAD
Jan 02 01:45:19 homeassistant-brains systemd[1]: systemd-timedated.service: Deactivated successfully.
Jan 02 01:45:19 homeassistant-brains kernel: audit: type=1334 audit(1704159919.400:210): prog-id=58 op=UNLOAD
Jan 02 01:45:19 homeassistant-brains kernel: audit: type=1334 audit(1704159919.400:211): prog-id=57 op=UNLOAD
Jan 02 01:45:19 homeassistant-brains kernel: audit: type=1334 audit(1704159919.400:212): prog-id=56 op=UNLOAD
Jan 02 01:46:13 homeassistant-brains NetworkManager[396]: <info>  [1704159973.2836] dhcp4 (enp1s0): state changed new lease, address=192.168.12.134
Jan 02 01:49:44 homeassistant-brains systemd-resolved[394]: Grace period over, resuming full feature set (UDP+EDNS0) for DNS server 192.168.12.254.
Jan 02 01:51:13 homeassistant-brains NetworkManager[396]: <info>  [1704160273.2746] dhcp4 (enp1s0): state changed new lease, address=192.168.12.134
Jan 02 01:51:33 homeassistant-brains NetworkManager[396]: <info>  [1704160293.6026] manager: NetworkManager state is now CONNECTED_SITE
Jan 02 01:51:33 homeassistant-brains systemd[1]: Starting Network Manager Script Dispatcher Service...
Jan 02 01:51:33 homeassistant-brains systemd[1]: Started Network Manager Script Dispatcher Service.
Jan 02 01:51:34 homeassistant-brains NetworkManager[396]: <info>  [1704160294.0680] manager: NetworkManager state is now CONNECTED_GLOBAL
Jan 02 01:51:44 homeassistant-brains systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
Jan 02 01:56:01 homeassistant-brains systemd[1]: Starting Cleanup of Temporary Directories...
Jan 02 01:56:01 homeassistant-brains systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
Jan 02 01:56:01 homeassistant-brains systemd[1]: Finished Cleanup of Temporary Directories.
Jan 02 01:56:01 homeassistant-brains systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dclean.service.mount: Deactivated successfully.
Jan 02 01:56:13 homeassistant-brains NetworkManager[396]: <info>  [1704160573.2748] dhcp4 (enp1s0): state changed new lease, address=192.168.12.134
Jan 02 01:58:16 homeassistant-brains systemd-resolved[394]: Grace period over, resuming full feature set (UDP+EDNS0) for DNS server 192.168.12.254.
Jan 02 01:58:16 homeassistant-brains systemd-resolved[394]: Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 192.168.12.254.
Jan 02 01:58:16 homeassistant-brains systemd-resolved[394]: Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 192.168.12.254.
Jan 02 02:01:13 homeassistant-brains NetworkManager[396]: <info>  [1704160873.2755] dhcp4 (enp1s0): state changed new lease, address=192.168.12.134
Jan 02 02:06:13 homeassistant-brains NetworkManager[396]: <info>  [1704161173.2768] dhcp4 (enp1s0): state changed new lease, address=192.168.12.134
Jan 02 02:11:13 homeassistant-brains NetworkManager[396]: <info>  [1704161473.2766] dhcp4 (enp1s0): state changed new lease, address=192.168.12.134
Jan 02 02:16:13 homeassistant-brains NetworkManager[396]: <info>  [1704161773.2842] dhcp4 (enp1s0): state changed new lease, address=192.168.12.134
Jan 02 02:18:43 homeassistant-brains kernel: audit: type=1334 audit(1704161923.353:213): prog-id=59 op=LOAD
Jan 02 02:18:43 homeassistant-brains systemd-timesyncd[467]: Network configuration changed, trying to establish connection.
Jan 02 02:18:43 homeassistant-brains systemd[1]: Started Journal Gateway Service.
Jan 02 02:18:43 homeassistant-brains systemd-journal-gatewayd[3115]: microhttpd: MHD_OPTION_EXTERNAL_LOGGER is not the first option specified for the daemon. Some messages may be printed by the standard MHD logger.
Jan 02 02:18:43 homeassistant-brains systemd-timesyncd[467]: Contacted time server 162.159.200.123:123 (time.cloudflare.com).

```
```


### System information

_No response_

### Additional information

_No response_

**Comment by wuyan1234837** [comment]
me too
