### ISSUE TITLE
Android app 

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/operating-system#3246]
### Describe the issue you are experiencing

Hello,

My HAOS/Rpi4-4GB/SSD has 3 devices which use the HA Android App (2 Samsung phones and 1 Wear OS device).  On occassion, but more prevelant since OS 12, upon rebooting the system either core or host, due to updates etc., the 2 samsung phones would stop report to HA and no information gets sent such as sensors, location and even NFC tag functions stop working. The integration loads as normal, and sensors are shown but they do not update. Typically, what ends up happening is another restart of either Core or Host solves the problem. However, since OS 12, I came into a situation where restarting host or core did not solve the issue. A complete shutdown of the the system, waiting and then rebooting fixed the problem.

With troubleshooting, there does not seem to be anything specific to this issue in the logs. The Android App logs, however, indicate a 503 error:

```
03-13 11:56:09.695  5699  6395 E SensorReceiver: Error while getting core config to sync sensor status
03-13 11:56:09.695  5699  6395 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 503 
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl.getConfig(IntegrationRepositoryImpl.kt:533)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at io.homeassistant.companion.android.common.data.integration.impl.IntegrationRepositoryImpl$getConfig$1.invokeSuspend(Unknown Source:14)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
03-13 11:56:09.695  5699  6395 E SensorReceiver: Caused by: retrofit2.HttpException: HTTP 503 
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-13 11:56:09.695  5699  6395 E SensorReceiver:     at java.lang.Thread.run(Thread.java:1012)
03-13 11:56:09.721  5699  6395 D ServerConnectionInfo: localUrl is: false, usesInternalSsid is: false
```

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

HAOS 12 and 12.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Reboot core or the host
2. Android devices do not send data to HA
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
unfortunatly, I do not have supervisor logs during this time.
```

### Anything in the Host logs that might be useful for us?

```txt
03-13 11:57:14.957  5699  6358 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: java.net.SocketTimeoutException: failed to connect to /192.168.1.xxx (port 8123) from /192.0.0.4 (port 55676) after 10000ms
```

and

```
03-13 11:56:10.629  5699  6395 E SensorReceiver: Error while getting core config to sync sensor status
03-13 11:56:10.629  5699  6395 E SensorReceiver: io.homeassistant.companion.android.common.data.integration.IntegrationException: retrofit2.HttpException: HTTP 503 ```
```

## System Information

version | core-2024.3.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | America/Edmonton
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4879
Installed Version | 1.34.0
Stage | running
Available Repositories | 1469
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 21, 2024 at 6:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-7.ui.nabu.casa
certificate_status | ready
instance_id | [redacted]
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | beta
supervisor_version | supervisor-2024.03.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 457.7 GB
disk_used | 33.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.2.0), Home Assistant Google Drive Backup (0.112.1), File editor (5.8.0), Samba share (12.3.1), AdGuard Home (5.0.4), Z-Wave JS UI (3.4.1), Glances (0.21.0), AppDaemon (0.16.4), Grafana (9.2.0), ESPHome (2024.2.2), Whisper (2.0.0), Piper (1.5.0), SQLite Web (4.1.2), Matter Server (5.4.1), openWakeWord (1.10.0), porcupine1 (1.2.0), Silicon Labs Multiprotocol (2.4.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 12
-- | --
resources | 13
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 1, 2024 at 3:52 PM
-- | --
current_recorder_run | March 13, 2024 at 12:34 PM
estimated_db_size | 1742.26 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by Anto79-ops** [comment]
thanks! I wasn't sure about this so will post it at core.

cheers
