### ISSUE TITLE
Unable to update from version 12.1to 12.2 on raspberry pi

### ISSUE THREAD

**Issue by Joernos** [home-assistant/operating-system#3341]
### Describe the issue you are experiencing

I'm not able to update from version 12.1 to 12.2 on my raspberry pi. It tries for about an hour before it ends without updating. I have the following running: core 2024.3.3. Os version 12 1. Supervisor 2024.04.4 system is online and reachable on the internet. 

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

12.1

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Just trying to upgrade from 12.1 to 12.2
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
supervisor.homeassistant.api] Updated Home Assistant API token
2024-05-05 14:30:16.401 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2024.5.1: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2024.5.1/json: Not Found ("No such image: ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2024.5.1")
2024-05-05 14:30:16.402 WARNING (MainThread) [supervisor.homeassistant.core] Updating Home Assistant image failed
```

### Anything in the Host logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:02:58 PM (1 occurrences)
Last logged: 5:02:58 PM

[547428643136] Error updating Home Assistant Operating System: Can't fetch OTA update from https://github.com/home-assistant/operating-system/releases/download/12.2/haos_rpi4-64-12.2.raucb:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 212, in async_install
    await async_update_os(self.hass, version)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 58, in _wrapper
    data = await funct(*argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 225, in async_update_os
    return await hassio.send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 592, in send_command
    raise HassioAPIError(error.get(ATTR_MESSAGE))
homeassistant.components.hassio.handler.HassioAPIError: Can't fetch OTA update from https://github.com/home-assistant/operating-system/releases/download/12.2/haos_rpi4-64-12.2.raucb: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 161, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 465, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 214, in async_install
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Operating System: Can't fetch OTA update from https://github.com/home-assistant/operating-system/releases/download/12.2/haos_rpi4-64-12.2.raucb:
```

### Additional information

I'm not able to update core from 2024.3.3 to 2024.5.1 either.  I have 21 GB of free space.

**Comment by Joernos** [comment]
Problem was internet.
