### ISSUE TITLE
ConBee II stick not working with ZHA (Connection Failed!)

### ISSUE THREAD

**Issue by 0xacloverfieldlane** [home-assistant/operating-system#3401]
### Describe the issue you are experiencing

Adding a ConBee II stick does not work. The stick will show up after starting to configure the ZHA, but after selecting it, it wants you to select a protocol, after that selecting DeConz and confirming the device path and baud rate it will say "Connection Failed!" with some errors in the log file.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

6.6.29-haos

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Have a ConBee II stick connected to the NUC running HAOS
2. Click on Add Devices and Choose "Zigbee Home Automation"
3. Try to configure with the ConBee II stick
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-06-06 14:23:08.897 INFO (SyncWorker_0) [supervisor.docker.manager] Restarting homeassistant
2024-06-06 14:23:16.544 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
2024-06-06 14:23:17.984 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-06-06 14:23:18.048 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-06-06 14:23:21.558 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to NOT_RUNNING
2024-06-06 14:23:26.570 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to RUNNING
2024-06-06 14:23:26.570 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
2024-06-06 14:24:05.266 INFO (MainThread) [supervisor.backups.manager] Found 3 backup files
2024-06-06 14:24:05.316 INFO (MainThread) [supervisor.backups.manager] Found 3 backup files
2024-06-06 14:26:34.011 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-06-06 14:33:53.408 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from a0d7b954_ssh
```

### Anything in the Host logs that might be useful for us?

```txt
2024-06-06 12:10:42.347 homeassistant systemd[1]: Finished Cleanup of Temporary Directories.
2024-06-06 12:16:11.794 homeassistant kernel: usb 1-4: USB disconnect, device number 2
2024-06-06 12:16:12.055 homeassistant kernel: usb 1-4: new full-speed USB device number 4 using xhci_hcd
2024-06-06 12:16:12.183 homeassistant kernel: usb 1-4: New USB device found, idVendor=1cf1, idProduct=0030, bcdDevice= 1.00
2024-06-06 12:16:12.184 homeassistant kernel: usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
2024-06-06 12:16:12.185 homeassistant kernel: usb 1-4: Product: ConBee II
2024-06-06 12:16:12.186 homeassistant kernel: usb 1-4: Manufacturer: dresden elektronik ingenieurtechnik GmbH
2024-06-06 12:16:12.186 homeassistant kernel: usb 1-4: SerialNumber: DE2678860
2024-06-06 12:16:12.189 homeassistant kernel: cdc_acm 1-4:1.0: ttyACM0: USB ACM device
2024-06-06 12:16:15.671 homeassistant kernel: usb 1-4: USB disconnect, device number 4
2024-06-06 12:16:15.987 homeassistant kernel: usb 1-4: new full-speed USB device number 5 using xhci_hcd
2024-06-06 12:16:16.115 homeassistant kernel: usb 1-4: New USB device found, idVendor=1cf1, idProduct=0030, bcdDevice= 1.00
2024-06-06 12:16:16.116 homeassistant kernel: usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
2024-06-06 12:16:16.117 homeassistant kernel: usb 1-4: Product: ConBee II
2024-06-06 12:16:16.117 homeassistant kernel: usb 1-4: Manufacturer: dresden elektronik ingenieurtechnik GmbH
2024-06-06 12:16:16.118 homeassistant kernel: usb 1-4: SerialNumber: DE2678860
2024-06-06 12:16:16.121 homeassistant kernel: cdc_acm 1-4:1.0: ttyACM0: USB ACM device
2024-06-06 12:17:56.866 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-a6c852fa72fd2bbb84e534fc9e766dc1b8500b70fe95ef8c7692a045ff5cfc03-runc.UA3qSq.mount: Deactivated successfully.
2024-06-06 12:23:16.326 homeassistant systemd[1]: docker-96e0df3741d717c115d13f5e7d15751fa820a85abe83dd5ea0ca945b91a0cd3c.scope: Deactivated successfully.
2024-06-06 12:23:16.326 homeassistant systemd[1]: docker-96e0df3741d717c115d13f5e7d15751fa820a85abe83dd5ea0ca945b91a0cd3c.scope: Consumed 53.714s CPU time.
2024-06-06 12:23:16.331 homeassistant kernel: kauditd_printk_skb: 6 callbacks suppressed
2024-06-06 12:23:16.331 homeassistant kernel: audit: type=1334 audit(1717676596.330:307): prog-id=89 op=UNLOAD
2024-06-06 12:23:16.343 homeassistant dockerd[554]: time="2024-06-06T12:23:16.342457636Z" level=info msg="ignoring event" container=96e0df3741d717c115d13f5e7d15751fa820a85abe83dd5ea0ca945b91a0cd3c module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
2024-06-06 12:23:16.509 homeassistant systemd[1]: Started libcontainer container 96e0df3741d717c115d13f5e7d15751fa820a85abe83dd5ea0ca945b91a0cd3c.
2024-06-06 12:23:16.521 homeassistant kernel: audit: type=1334 audit(1717676596.520:308): prog-id=90 op=LOAD
2024-06-06 12:23:16.521 homeassistant kernel: audit: type=1300 audit(1717676596.520:308): arch=c000003e syscall=321 success=yes exit=15 a0=5 a1=c00011d928 a2=78 a3=0 items=0 ppid=9797 pid=9806 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
2024-06-06 12:23:16.521 homeassistant kernel: audit: type=1327 audit(1717676596.520:308): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F39366530646633373431643731376331313564313366356537
2024-06-06 12:23:16.521 homeassistant kernel: audit: type=1334 audit(1717676596.520:309): prog-id=91 op=LOAD
2024-06-06 12:23:16.521 homeassistant kernel: audit: type=1300 audit(1717676596.520:309): arch=c000003e syscall=321 success=yes exit=17 a0=5 a1=c00011d6c0 a2=78 a3=0 items=0 ppid=9797 pid=9806 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
2024-06-06 12:23:16.521 homeassistant kernel: audit: type=1327 audit(1717676596.520:309): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F39366530646633373431643731376331313564313366356537
2024-06-06 12:23:16.521 homeassistant kernel: audit: type=1334 audit(1717676596.520:310): prog-id=91 op=UNLOAD
2024-06-06 12:23:16.521 homeassistant kernel: audit: type=1300 audit(1717676596.520:310): arch=c000003e syscall=3 success=yes exit=0 a0=11 a1=0 a2=0 a3=0 items=0 ppid=9797 pid=9806 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
2024-06-06 12:23:16.521 homeassistant kernel: audit: type=1327 audit(1717676596.520:310): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F72756E2F636F6E7461696E6572642F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F39366530646633373431643731376331313564313366356537
```

## System Information

version | core-2024.6.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1392
Downloaded Repositories | 4
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 6. Juli 2024 um 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-20.ui.nabu.casa
certificate_status | ready
instance_id | [redacted]
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 13.4 GB
disk_used | 8.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.14.0), File editor (5.8.0), ESPHome (2024.5.5), openWakeWord (1.10.0), Assist Microphone (1.2.0), Whisper (2.1.0), Piper (1.5.0), Advanced SSH & Web Terminal (18.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3. Juni 2024 um 20:30
-- | --
current_recorder_run | 6. Juni 2024 um 14:23
estimated_db_size | 125.91 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Additional information

**home-assistant.log**
```
2024-06-06 14:25:24.893 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by integration 'zha' at homeassistant/components/zha/radio_manager.py, line 221: probe_result = await r>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main 
 File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/zha/config_flow.py", line 204, in async_step_choose_serial_port
    probe_result = await self._radio_mgr.detect_radio_type()
  File "/usr/src/homeassistant/homeassistant/components/zha/radio_manager.py", line 221, in detect_radio_type
    probe_result = await radio.controller.probe(dev_config)
```
**ls -l /dev/serial/by-id**
```
total 0
lrwxrwxrwx    1 root     root            13 Jun  6 14:16 usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2678860-if00 -> ../../ttyACM0
```

**Comment by sairon** [comment]
I don't see anything wrong in the OS logs and the serial device seems to work correctly. The stack trace from the ZHA integration is not complete though, so it's hard to tell what the error is. Anyway, I think it's an issue with the ZHA integration (or the general setup - like concurrent access to the port), not with the OS, so please get the complete error message and file an issue in the Core repository for the ZHA integration.
