### ISSUE TITLE
Z2M with Sonoff Dongle E stopped working after OS upgrade to 13.2

### ISSUE THREAD

**Issue by xsirpreisx** [home-assistant/operating-system#3649]
### Describe the issue you are experiencing

Hi,

not sure if it's ok to post my issue here...

Today I upgraded the Raspberry Pi HA OS from 13.1 to 13.2.

Afterwards, Z2M with the Sonoff Dongle E stopped working and I have no idea how to make it work again. In 13.1 there were no issues.

Z2M Configuration as follows (the path is the one that worked before, and I can still see that path in the "all hardware" view in HA):

![image](https://github.com/user-attachments/assets/11f2530c-0231-47f0-afc1-624ada536e02)

The firmware for the Sonoff dongle is on the latest current version (I think it’s 7.4.4). That firmware worked fine for a few weeks now, but the whole thing stopped working after upgrading HA OS to 13.2.

I reflashed the most current firmware, rebooted my Pi4, removed the USB extension cable to connect the Sonoff directly to the Pi, also used a different USB slot… Nothing works. I always get this:

`
[18:58:27] INFO: Preparing to start...
[18:58:27] INFO: Socat not enabled
[18:58:30] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-10-23 18:58:36] info: 	z2m: Logging to console, file (filename: log.log)
[2024-10-23 18:58:36] info: 	z2m: Starting Zigbee2MQTT version 1.40.2 (commit #unknown)
[2024-10-23 18:58:36] info: 	z2m: Starting zigbee-herdsman (2.1.3)
[2024-10-23 18:58:37] info: 	zh:ember: Using default stack config.
[2024-10-23 18:58:37] info: 	zh:ember: ======== Ember Adapter Starting ========
[2024-10-23 18:58:37] info: 	zh:ember:ezsp: ======== EZSP starting ========
[2024-10-23 18:58:37] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-10-23 18:58:37] info: 	zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2024-10-23 18:58:37] info: 	zh:ember:uart:ash: Serial port opened
[2024-10-23 18:58:37] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-23 18:58:40] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-10-23 18:58:40] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-23 18:58:42] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-10-23 18:58:42] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-23 18:58:45] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-10-23 18:58:45] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-23 18:58:47] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-10-23 18:58:47] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-23 18:58:50] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-23 18:58:50] error: 	z2m: Failed to start zigbee
[2024-10-23 18:58:50] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-23 18:58:50] error: 	z2m: Exiting...
[2024-10-23 18:58:50] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:684:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1583:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
`

Any ideas?

### What operating system image do you use?

rpi4-64  (Raspberry Pi 4/400 64-bit OS)

### What version of Home Assistant Operating System is installed?

13.2

### Did the problem occur after upgrading the Operating System?

Yes

### Hardware details

Raspberry Pi 4, 8 GB RAM

### Steps to reproduce the issue

1. On OS 13.1 with Zigbee Sonoff Dongle-E and Z2M everything worked
2. Upgrade OS to 13.2
3. Z2M crashing.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the Host logs that might be useful for us?

```txt
-
```

**Comment by xsirpreisx** [comment]
I downgraded HA OS back to 13.1... and the problem is still there. So I have no idea why it's happening, but probably not due to 13.2.
