### ISSUE TITLE
Unable to update from 14.0 to 14.1

### ISSUE THREAD

**Issue by MattN82** [home-assistant/operating-system#3761]
### Describe the issue you are experiencing

Hi,

I'm running HA as a proxmox vm.

Starting the update from 14.0 to 14.1 gives me an error:

_Error updating Home Assistant Operating System: Can't fetch OTA update from https://os-artifacts.home-assistant.io/14.1/haos_ova-14.1.raucb: Cannot connect to host os-artifacts.home-assistant.io:443 ssl:default [Could not contact DNS servers]_

I've made no changes to the system recently.

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

6.6.63

### Did the problem occur after upgrading the Operating System?

No

### Hardware details

Generic proxmox vm with 4 cpus and 16 Gb Ram

### Steps to reproduce the issue

1.Click "Update" (14..0 -> 14.1)
2.Read Error Message
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:245
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 10:36:39 (15 Vorkommnisse)
Zuletzt protokolliert: 11:16:19

[139677219453056] Unexpected exception
[139676642829952] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 214, in async_install
    await self.coordinator.supervisor_client.os.update(
        OSUpdate(version=version)
    )
  File "/usr/local/lib/python3.13/site-packages/aiohasupervisor/os.py", line 28, in update
    await self._client.post(
        "os/update", json=options.to_dict() if options else None, timeout=None
    )
  File "/usr/local/lib/python3.13/site-packages/aiohasupervisor/client.py", line 173, in post
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohasupervisor/client.py", line 122, in _request
    raise exc_type(result.message, result.job_id)
aiohasupervisor.exceptions.SupervisorBadRequestError: 'OSManager.update' blocked from execution, system is not running - startup

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 502, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 218, in async_install
    raise HomeAssistantError(
        f"Error updating Home Assistant Operating System: {err}"
    ) from err
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Operating System: 'OSManager.update' blocked from execution, system is not running - startup
```

### Anything in the Host logs that might be useful for us?

```txt
Note: "xxx.yyy.z.z" is a placeholder for the actual ip

2024-12-21 10:16:11.382 homeassistant dockerd[471]: time="2024-12-21T10:16:11.382821034Z" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.30.232.2:58143" dns-server="udp:xxx.yyy.z.z:53" error="read udp 172.30.232.2:58143->xxx.yyy.z.z:53: i/o timeout" question=";os-artifacts.home-assistant.io.\tIN\t AAAA"
2024-12-21 10:16:11.383 homeassistant dockerd[471]: time="2024-12-21T10:16:11.382821173Z" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.30.232.2:35338" dns-server="udp:xxx.yyy.z.z:53" error="read udp 172.30.232.2:35338->xxx.yyy.z.z:53: i/o timeout" question=";os-artifacts.home-assistant.io.\tIN\t A"
2024-12-21 10:16:15.384 homeassistant dockerd[471]: time="2024-12-21T10:16:15.384792810Z" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.30.232.2:35254" dns-server="udp:xxx.yyy.z.z:53" error="read udp 172.30.232.2:35254->xxx.yyy.z.z:53: i/o timeout" question=";os-artifacts.home-assistant.io.\tIN\t AAAA"
2024-12-21 10:16:15.385 homeassistant dockerd[471]: time="2024-12-21T10:16:15.384807259Z" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.30.232.2:50098" dns-server="udp:xxx.yyy.z.z:53" error="read udp 172.30.232.2:50098->xxx.yyy.z.z:53: i/o timeout" question=";os-artifacts.home-assistant.io.\tIN\t A"
2024-12-21 10:16:19.385 homeassistant dockerd[471]: time="2024-12-21T10:16:19.385787831Z" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.30.232.2:32882" dns-server="xxx.yyy.z.z:53" error="read udp 172.30.232.2:32882->xxx.yyy.z.z:53: i/o timeout" question=";os-artifacts.home-assistant.io.\tIN\t AAAA"
2024-12-21 10:16:19.386 homeassistant dockerd[471]: time="2024-12-21T10:16:19.386062609Z" level=error msg="[resolver] failed to query external DNS server" client-addr="udp:172.30.232.2:44616" dns-server="udp:xxx.yyy.z.z:53" error="read udp 172.30.232.2:44616->xxx.yyy.z.z:53: i/o timeout" question=";os-artifacts.home-assistant.io.\tIN\t A"
```

## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.63-haos
arch | x86_64
timezone | 
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4986
Installed Version | 2.0.1
Stage | running
Available Repositories | 1496
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: timeout
can_reach_cloud_auth | failed to load: timeout
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 8.4 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | false
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (19.0.0), File editor (5.8.0), FTP (5.1.1)

</details>

**Comment by MattN82** [comment]
I found the origin of the problem. not a HA issue. A faulty pihole instance caused only parts of the connections to fail. 

Issue resolved...no action required
